### PR TITLE
Define custom cereal override for ConfigUpgradeSetKey and use it

### LINKED ISSUE #4246: wrong format used for contract ID when scheduling Soroban network upgrades
After arming a phase 2 upgrade, core `info` returns
```json
      "status" : [
         "Armed with network upgrades: upgradetime=2024-03-19T16:00:00Z, configupgradesetkey = {\n  contractID = bcc748055098ece70fb97dc327141083a772b33c07220cc16c134642ec4fc4e9,\n  content
Hash = 2b3ea4cc865ace6e6c2ceaf9e19b1301cd09191d58fc21f889bc9b62a1d5c6f5\n}\n"
      ]
```

the contractID should be the strkey `CC6MOSAFKCMOZZYPXF64GJYUCCB2O4VTHQDSEDGBNQJUMQXMJ7COSZSN` instead

missed when addressing https://github.com/stellar/stellar-core/issues/4184

### PR DESCRIPTION
**Pull request by sisuresh**
# Description

Resolves #4246 

The new output now looks like - 
```
[Herder INFO] Armed with network upgrades: upgradetime=2000-07-21T22:04:00Z, {
    "configupgradesetkey": {
        "contractID": "CDEWOG5BY6RL6HPKAO5GUPMZDEW2Y22V3J7PHI3WZN7HASTWGTMI6ITO",
        "contentHash": "7fa751106b2a7988dea3af733ca86484f1581f97c2ec9553bb36d402c612847d"
    }
}
```

# Checklist
- [ ] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [ ] Rebased on top of master (no merge commits)
- [ ] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [ ] Compiles
- [ ] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/herder/Upgrades.cpp [hunk 1]
```diff
@@ -393,7 +393,7 @@ Upgrades::toString(LedgerUpgrade const& upgrade)
     case LEDGER_UPGRADE_CONFIG:
         return fmt::format(
             FMT_STRING("{}"),
-            xdr::xdr_to_string(upgrade.newConfig(), "configupgradesetkey"));
```
Comment (sisuresh) [inline src/herder/Upgrades.cpp:396]: This was confusing to figure out. We have two different `xdr_to_string` methods. One in [xdrpp](https://github.com/xdrpp/xdrpp/blob/8756126cc734c11b75e05f174ca35a192860d0a6/xdrpp/printer.h#L162), and one in [XDRCereal.h](https://github.com/stellar/stellar-core/blob/master/src/util/XDRCereal.h#L186). I added a `cereal_override` but it did nothing because we were using the xdrpp methods. Maybe we should rename, add a namespace, or stop using the xdrpp method altogether.

**Comment by dmkozh** [comment]
r+ f3ffbbe
