### PR TITLE
Simulation updates and fixes

### LINKED ISSUE #3285: WorkScheduler::executeWork is wrong
We have logic in the code that allows to synchronously execute work. However, the blocking condition isn't right, as the function is waiting for all children to complete, not just the desired work: https://github.com/stellar/stellar-core/blob/e154cb2e31363aa5b87420cfa37cae00b2fb071b/src/work/WorkScheduler.h#L37

I believe @sisuresh already has a fix for this as part of the other simulation changes, but I'm opening an issue to track this bug properly.

### PR DESCRIPTION
**Pull request by sisuresh**
# Description

Resolves #3285 and brings simulation up to date with protocol 18.

# Checklist
- [ ] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [ ] Rebased on top of master (no merge commits)
- [ ] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [ ] Compiles
- [ ] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/transactions/simulation/TxSimUtils.cpp [hunk 1]
```diff
@@ -212,10 +213,51 @@ mutateScaledAccountID(MuxedAccount& acc, uint32_t partition)
     return key;
 }
 
+PoolID
+getPoolID(LiquidityPoolConstantProductParameters const& params)
```
Comment (marta-lokhova) [inline src/transactions/simulation/TxSimUtils.cpp:217]: Would it be possible to reuse logic we already have in the codebase to generate this id? i.e. OfferExchange::getPoolID

File: src/transactions/simulation/TxSimUtils.cpp [hunk 2]
```diff
@@ -212,10 +213,51 @@ mutateScaledAccountID(MuxedAccount& acc, uint32_t partition)
...
+{
+    LiquidityPoolParameters lpp(LIQUIDITY_POOL_CONSTANT_PRODUCT);
+    lpp.constantProduct() = params;
+    return xdrSha256(lpp);
+}
+
+PoolID
+getScaledPoolID(AbstractLedgerTxn& ltx, PoolID const& poolID,
+                UnorderedMap<PoolID, LiquidityPoolParameters>& ctPoolIdToParam,
```
Comment (marta-lokhova) [inline src/transactions/simulation/TxSimUtils.cpp:226]: use const ref

File: src/transactions/simulation/TxSimUtils.cpp [hunk 3]
```diff
@@ -212,10 +213,51 @@ mutateScaledAccountID(MuxedAccount& acc, uint32_t partition)
...
+    if (!pool)
+    {
+        // This pool may be created in the same ledger
+        auto it = ctPoolIdToParam.find(poolID);
+        if (it != ctPoolIdToParam.end())
+        {
+            auto params = it->second;
+            replaceIssuer(params.constantProduct().assetA, partition);
+            replaceIssuer(params.constantProduct().assetB, partition);
+            return xdrSha256(params);
```
Comment (marta-lokhova) [inline src/transactions/simulation/TxSimUtils.cpp:239]: same thing here, let's use the same `getPoolID` functionality everywhere. The same sequence of events happens later in this function on line 247, so it also can be extracted into a function

File: src/transactions/simulation/TxSimUtils.cpp [hunk 4]
```diff
@@ -212,10 +213,51 @@ mutateScaledAccountID(MuxedAccount& acc, uint32_t partition)
...
+
 void
-generateScaledLiveEntries(std::vector<LedgerEntry>& entries,
-                          std::vector<LedgerEntry> const& oldEntries,
-                          uint32_t partition)
+generateScaledLiveEntries(
+    std::vector<LedgerEntry>& entries,
+    std::vector<LedgerEntry> const& oldEntries,
+    UnorderedMap<PoolID, LiquidityPoolConstantProductParameters> const&
+        mPoolIDToAssets,
```
Comment (marta-lokhova) [inline src/transactions/simulation/TxSimUtils.cpp:259]: nitpick: naming conversion here and in other places. also the naming for this map varies across the file: here it's poolIDToAsset, but in other places it's poolIDToParam. Using the same name would improve clarity.

File: src/catchup/simulation/TxSimApplyTransactionsWork.cpp [hunk 5]
```diff
@@ -411,7 +411,11 @@ TxSimApplyTransactionsWork::scaleLedger(
     // First, update transaction source accounts
     LedgerTxn ltx(mApp.getLedgerTxnRoot());
     mutateTxSourceAccounts(newEnv, ltx, keys, partition);
-    mutateOperations(newEnv, ltx, keys, partition);
+
+    // Maps PoolID from ChangeTrustOp to the LiquidityPoolParameters so we can
+    // scale poolIds for pools created and deposited into in the same ledger
+    UnorderedMap<PoolID, LiquidityPoolParameters> ctPoolIdToParam;
```
Comment (marta-lokhova) [inline src/catchup/simulation/TxSimApplyTransactionsWork.cpp:417]: Seems like `mutateOperations` does not really need `ctPoolIdToParam`, as it can be tracked inside the function

File: src/transactions/simulation/TxSimUtils.cpp [hunk 6]
```diff
@@ -428,10 +522,87 @@ mutateScaledOperation(Operation& op, uint32_t partition)
...
+            op.body.beginSponsoringFutureReservesOp().sponsoredID, partition);
+        break;
+    case REVOKE_SPONSORSHIP:
+        if (op.body.revokeSponsorshipOp().type() ==
+            REVOKE_SPONSORSHIP_LEDGER_ENTRY)
+        {
+            auto& key = op.body.revokeSponsorshipOp().ledgerKey();
+            switch (key.type())
+            {
+            case ACCOUNT:
```
Comment (marta-lokhova) [inline src/transactions/simulation/TxSimUtils.cpp:536]: The logic here is identical to `TxSimUtils::generateScaledDeadEntries`, so we should refactor this to avoid duplication

File: src/catchup/simulation/TxSimApplyTransactionsWork.cpp (hunk 5 above)
Comment (marta-lokhova) [reply src/catchup/simulation/TxSimApplyTransactionsWork.cpp:417]: Also, loading LPs from the DB during scaling may have a pretty noticeable performance impact, so you may want to consider caching simulated LP mappings.

File: src/transactions/simulation/TxSimUtils.cpp [hunk 7]
```diff
@@ -178,6 +178,15 @@ generateScaledClaimableBalanceID(Hash const& balanceID, uint32_t partition)
     return scaledID;
 }
 
+SignerKey
+generateScaledEd25519Signer(SignerKey const& signer, uint32_t partition)
```
[the remark this answers is not in the document]
Comment (sisuresh) [reply src/transactions/simulation/TxSimUtils.cpp:193]: Done

File: src/transactions/simulation/TxSimUtils.cpp [hunk 8]
```diff
@@ -290,6 +299,16 @@ generateScaledLiveEntries(std::vector<LedgerEntry>& entries,
             }
             break;
         }
+        case LIQUIDITY_POOL:
+        {
+            auto& cp = newEntry.data.liquidityPool().body.constantProduct();
+            replaceIssuer(cp.params.assetA, partition);
```
[the remark this answers is not in the document]
Comment (sisuresh) [reply src/transactions/simulation/TxSimUtils.cpp]: Yeah good catch. Should be fixed now.

File: src/transactions/simulation/TxSimUtils.cpp (hunk 1 above)
Comment (sisuresh) [reply src/transactions/simulation/TxSimUtils.cpp]: I reworked some of this and think it makes sense to keep the new poolID methods separate from the one in OfferExchange.

File: src/transactions/simulation/TxSimUtils.cpp (hunk 2 above)
Comment (sisuresh) [reply src/transactions/simulation/TxSimUtils.cpp]: Done

File: src/transactions/simulation/TxSimUtils.cpp (hunk 3 above)
Comment (sisuresh) [reply src/transactions/simulation/TxSimUtils.cpp]: Done

File: src/transactions/simulation/TxSimUtils.cpp (hunk 4 above)
Comment (sisuresh) [reply src/transactions/simulation/TxSimUtils.cpp]: Good catch. Fixed.

File: src/catchup/simulation/TxSimApplyTransactionsWork.cpp (hunk 5 above)
Comment (sisuresh) [reply src/catchup/simulation/TxSimApplyTransactionsWork.cpp]: Moved `ctPoolIdToParam` into `mutateOperations`. For your second point, wouldn't `mEntryCache` in `LedgerTxnRoot` cache the LP after the first query? Or am I misunderstanding?

File: src/transactions/simulation/TxSimUtils.cpp (hunk 6 above)
Comment (sisuresh) [reply src/transactions/simulation/TxSimUtils.cpp]: Done.

File: src/transactions/simulation/TxSimGenerateBucketsWork.cpp [hunk 9]
```diff
@@ -116,6 +119,59 @@ TxSimGenerateBucketsWork::processGeneratedBucket()
 BasicWork::State
 TxSimGenerateBucketsWork::onRun()
 {
+    if (!mPoolIdMappingDone)
```
[the remark this answers is not in the document]
Comment (sisuresh) [reply src/transactions/simulation/TxSimGenerateBucketsWork.cpp:122]: I tried changing the iteration order, but I was getting the error `Invalid HAS: future must have resolved output`. I looked into it but the issue wasn't clear to me. I'd like to discuss with you before I spend more time on this.

[the remark this answers is not in the document]
Comment (sisuresh) [reply src/transactions/simulation/TxSimGenerateBucketsWork.cpp]: I removed this logic and reversed the iteration order of the buckets to get this to work.

[the remark this answers is not in the document]
Comment (marta-lokhova) [reply src/transactions/simulation/TxSimGenerateBucketsWork.cpp]: great, thanks! resolving

**Review by marta-lokhova — APPROVED** [review]
Looks good! Please squash the commits and we can merge

**Review by marta-lokhova — APPROVED** [review]

**Comment by marta-lokhova** [comment]
r+ 164b2a012e55ebdcfb699c5e7b4f36915132ca79
