### PR TITLE
Fix parallel cluster tx queue instruction limit

### LINKED ISSUE #4886: Transaction Queue limits should scale ledger instruction limit with the number of clusters
The Soroban ledger sequential instruction limit is enforced per cluster,  so an increase to `ledgerMaxDependentTxClusters` can result in more Soroban transactions being included in a ledger. The issue here is that the `TxQueueLimiter` doesn't take `ledgerMaxDependentTxClusters` into account, so it'll reject transactions that could make it into the ledger.

### PR DESCRIPTION
**Pull request by SirTyson**
# Description

Resolves #4886

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Review by dmkozh — APPROVED** [review]

**Comment by SirTyson** [comment]
There's  a possibility of int_64 overflow since we multiple max instructions by cluster count. For now, I've added a check such that network config settings upgrade is not valid if max ledger instructions * cluster count overflows. We might still overflow later in the tx queue logic, since we do maxInstruction * clsuterCount * 2, but since it's just the TX queue, I just cap that multiple to int_64 max.  The saturating multiple in `maxLedgerResources` shouldn;t be necessary because of the network config check, but I added it just to be safe.

File: src/ledger/NetworkConfig.cpp [hunk 1]
```diff
@@ -1061,6 +1062,18 @@ SorobanNetworkConfig::isValidConfigSettingEntry(ConfigSettingEntry const& cfg,
                     cfg.contractCompute().txMaxInstructions &&
                 cfg.contractCompute().txMemoryLimit >=
                     MinimumSorobanNetworkConfig::MEMORY_LIMIT;
+
+        // In protocol V23+, check that ledgerMaxInstructions * clusters won't
```
Comment (dmkozh) [inline src/ledger/NetworkConfig.cpp]: I think this is going to break the 'unlimited resources' use case of core for standalone builds. We already check the tx sets for overflows of the actual per-cluster resources, as well as the total resource sums. In combination with the saturating multiplication for the tx queue, I think we should be fine with any configuration.
