### PR TITLE
Move expiration enforcement to OpFrame level

### LINKED ISSUE #3854: Move state expiration enforcement from LedgerTxn to TransactionFrame level
Following the Preview 10 crashes, we changed the way BucketList models state expiration. Due to this, we need to move the state expiration up a level in abstraction from the LedgerTxn level to the transaction/OpFrame level.

### PR DESCRIPTION
**Pull request by SirTyson**
# Description

Resolves #3854 and #3850.

This change moves state expiration enforcement to the `InvokeHostFunctionOpFrame` level. By doing so, the database and "ledger state" is agnostic to expiration semantics. This simplifies BucketList invariants and makes it easier for downstream systems to ingest state related meta. This resolves the issue that crashed preview 10.

This PR also adds more state expiration unit tests.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Review by dmkozh — COMMENTED** [review]
Looks fine overall, but shouldn't we also update the bump op as well to only bump live entries?

**Comment by sisuresh** [comment]
> Looks fine overall, but shouldn't we also update the bump op as well to only bump live entries?

Yeah this is a good catch. This PR switches `load` from returning live entries to all entries, so the bump op in this PR now allows bumps to expired entries. We need to audit every `load` call that can load a soroban entry and make sure the logic makes sense.

File: src/herder/Upgrades.cpp [hunk 1]
```diff
@@ -1300,8 +1300,7 @@ ConfigUpgradeSetFrameConstPtr
 ConfigUpgradeSetFrame::makeFromKey(AbstractLedgerTxn& ltx,
                                    ConfigUpgradeSetKey const& key)
 {
-    auto ltxe = ltx.loadWithoutRecord(ConfigUpgradeSetFrame::getLedgerKey(key),
-                                      /*loadExpiredEntry=*/false);
+    auto ltxe = ltx.loadWithoutRecord(ConfigUpgradeSetFrame::getLedgerKey(key));
```
Comment (sisuresh) [inline src/herder/Upgrades.cpp:1303]: This is interesting... we don't check if the entry is live here, so we can technically upgrade using an expired entry. Should we keep this as is for more flexibility? Or should we make sure the entry is live? Checking that it's live sounds more consistent. cc @dmkozh.

File: src/main/CommandHandler.cpp [hunk 2]
```diff
@@ -720,7 +720,7 @@ CommandHandler::getLedgerEntry(std::string const& params, std::string& retStr)
 
         LedgerKey k;
         fromOpaqueBase64(k, key);
-        auto le = ltx.loadWithoutRecord(k, /*loadExpiredEntry=*/false);
```
Comment (sisuresh) [inline src/main/CommandHandler.cpp:723]: This command will now return expired entries, when it previously didn't . I'm guessing returning expired entries is what we want, but want to make sure we didn't have a good reason for ignoring them in the first place.

File: src/herder/Upgrades.cpp (hunk 1 above)
Comment (SirTyson) [reply src/herder/Upgrades.cpp:1303]: I don't have a great understanding of the upgrade system, but allowing anything to use an expired entry seems very sketchy (except for restoreOp of course). I think we should add a `isLive` check here.

File: src/main/CommandHandler.cpp (hunk 2 above)
Comment (SirTyson) [reply src/main/CommandHandler.cpp:723]: This should return expired entries. This is used for services like soroban-rpc to track state, and it would be helpful for these systems to know about expired entries. This not returning expired entries before was a bug.

File: src/herder/Upgrades.cpp (hunk 1 above)
Comment (dmkozh) [reply src/herder/Upgrades.cpp:1303]: Yeah, I don't think we should need exceptions to the rules.

**Comment by sisuresh** [comment]
r+ 0ad2053d5f0d5c7e6db05470b328987f23adeecc
