### PR TITLE
Bug 2267 quorum intersection pick any scc with a quorum

### LINKED ISSUE #2267: Potentially incorrect quorum intersection check (Version: 11.4.0)
While implementing the quorum intersection check in Python in [stellar-observatory](https://github.com/andrenarchy/stellar-observatory) (as part of an SDF-supported academic research project) with @liamsi we noticed a potential issue in the corresponding Stellar Core implementation. It seems to be implemented incorrectly in the part where strongly connected components of the induced dependency/reachability graph are handled:

* In the [paper by Lachowski](https://arxiv.org/abs/1902.06493v1) the "greatest element" or "top" has a special meaning: it is meant with respect to the topological (reachability) order, i.e., the "top" component element cannot "reach" other components. See also the [discussion on PaperHive](https://paperhive.org/documents/items/ACdED1EekRhH?a=d:-_U0EJUs92Ng).
* In Core it seems to use the biggest component (i.e., by the number of elements), see [here](https://github.com/stellar/stellar-core/blob/27576172e99d89cbacfe6571f807a5e85746f618/src/herder/QuorumIntersectionCheckerImpl.cpp#L680).

This means that the algorithm would be looking at the wrong strongly connected component if there is a component that is bigger than the top component in the topological order, thus giving wrong results.

### PR DESCRIPTION
**Pull request by graydon**
# Description

Resolves #2267 in a different way than #2278. Simpler: just pick the first quorum-containing SCC we find, and fail if there's more than one (as we were already doing). Avoids artificially picking an SCC with no quorums that happens to just be "big".

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by graydon** [comment]
@fixxxedpoint is this more along the correct line of behaviour?

File: src/herder/QuorumIntersectionCheckerImpl.cpp [hunk 1]
```diff
@@ -674,18 +674,19 @@ void
 QuorumIntersectionCheckerImpl::buildSCCs()
 {
     mTSC.calculateSCCs();
-    mMaxSCC.clear();
+    mScanSCC.clear();
     for (auto const& scc : mTSC.mSCCs)
```
Comment (fixxxedpoint) [inline src/herder/QuorumIntersectionCheckerImpl.cpp]: I would just remove that loop together with mScanSCC class variable and merge it with that main loop in networkEnjoysQuorumIntersection(). Name suggests it is only responsible for building SCCs and the whole thing will be also more easier to understand (as we talked before, you don't need to search for that greatest element). It is not a big deal but current version also iterates all SCCs twice.

Comment (graydon) [reply src/herder/QuorumIntersectionCheckerImpl.cpp]: @fixxxedpoint Well, mScanSCC is used in a couple other helper methods throughout the implementation, I can't easily eliminate it entirely without turning it into a parameter I have to pass everywhere; but I can merge the setup loops as you suggest. Will do so. Otherwise I just wanted to double check: style issues aside, this at least looks _correct_ to you?

Thanks again for all the input and hand-holding; I just want to make sure I'm faithfully transplanting your work here :)

Comment (graydon) [reply src/herder/QuorumIntersectionCheckerImpl.cpp]: (Update: actually making the variable local / sinking it into a member into the helper class was relatively low-impact; patch updated with the results!)

**Comment by MonsieurNicolas** [comment]
r+ c2d9b9e564ed4520f205a0b1cd6016652a99152f
