### PR TITLE
ApplyLedgerWork fails correctly

### LINKED ISSUE #3131: crash when failing to catchup
Looks like recent changes cause core to crash when catching up and there is a hash mismatch (offline catchup).

```
2021-07-14T22:55:48.298 GD7I3 [Tx INFO] applying ledger 247686 (txs:4, ops:6)
2021-07-14T22:55:48.323 GD7I3 [Tx INFO] applying ledger 247687 (txs:3, ops:9)
2021-07-14T22:55:48.364 GD7I3 [Tx INFO] applying ledger 247688 (txs:4, ops:6)
2021-07-14T22:55:48.398 GD7I3 [Tx INFO] applying ledger 247689 (txs:2, ops:5)
2021-07-14T22:55:48.421 GD7I3 [Tx INFO] applying ledger 247690 (txs:4, ops:9)
2021-07-14T22:55:48.476 GD7I3 [History ERROR] Replay failed: Local node's ledger corrupted during close
2021-07-14T22:55:48.476 GD7I3 [History ERROR] Archive core_testnet_002 maybe contains corrupt file transactions/00/03/c7/transactions-0003c7bf.xdr.gz
stellar-core: work/BasicWork.cpp:47: virtual stellar::BasicWork::~BasicWork(): Assertion `isDone() || mState == InternalState::PENDING' failed.

Aborted (core dumped)
```

I suspect this is related to how we shutdown (again).

### PR DESCRIPTION
**Pull request by marta-lokhova**
Resolves #3131

### CODE REVIEW

File: src/catchup/ApplyCheckpointWork.cpp [hunk 1]
```diff
@@ -323,12 +323,6 @@ ApplyCheckpointWork::onRun()
         mConditionalWork->startWork(wakeSelfUpCallback());
         return State::WORK_RUNNING;
     }
-    catch (InvariantDoesNotHold&)
-    {
-        // already displayed e.what()
-        CLOG_ERROR(History, "Replay failed");
-        throw;
-    }
```
Comment (MonsieurNicolas) [inline src/catchup/ApplyCheckpointWork.cpp:331]: you can stop including the related header

Comment (MonsieurNicolas) [reply src/catchup/ApplyCheckpointWork.cpp:331]: that said... I think the intent of the throw here was to ensure that we get a core dump in this kind of situation

Comment (MonsieurNicolas) [reply src/catchup/ApplyCheckpointWork.cpp:331]: never mind: this exception cannot happen anymore as we queue up an `ApplyLedgerWork`, this was missed when we made the `ApplyLedgerWork` change

File: src/catchup/ApplyLedgerWork.cpp [hunk 2]
```diff
@@ -23,7 +24,15 @@ BasicWork::State
 ApplyLedgerWork::onRun()
 {
     ZoneScoped;
-    mApp.getLedgerManager().closeLedger(mLedgerCloseData);
+    try
+    {
+        mApp.getLedgerManager().closeLedger(mLedgerCloseData);
+    }
+    catch (std::exception const& e)
```
Comment (MonsieurNicolas) [inline src/catchup/ApplyLedgerWork.cpp:31]: I am not quite sure this is the right fix:
with this change, we stop crashing if there is some catastrophic problem when closing a ledger, and just retry etc

the reason we want to crash is that the core file may contain critical information that would allow to diagnose the issue.

I *think* that the original problem is not so much that we crash but that we crash with the wrong context (an assert in Work).

Comment (MonsieurNicolas) [reply src/catchup/ApplyLedgerWork.cpp:31]: Looking at the kind of exceptions that `CloseLedger` can throw, I am not sure there are any situations where we want to fail the "work" as all situations indicate some severe problem with the local node
(I was trying to see if we should crash only for a subset of exceptions, like what was done before in `ApplyCheckpointWork`)

**Review by MonsieurNicolas — CHANGES_REQUESTED** [review]

**Comment by MonsieurNicolas** [comment]
r+ d3b9ddea5bcd393352a92148a1d93caa4b5a4e76
