### PR TITLE
fsync on BucketIndex writes

### LINKED ISSUE #4546: Bucket index files corruption
Observed on a validator, the problem occurred when core shutdown while re-indexing buckets
```
current exception: std::runtime_error("Failed to read 4 bytes from input stream! Read 0")
stellar-core.service: Main process exited, code=killed, status=6
```

### PR DESCRIPTION
**Pull request by SirTyson**
# Description

Resolves #4546

This change calls fsync after writing `BucketIndex` files. This change was slightly more involved than expected. There's no way to fall fsync on files opened via `std::fstream`, so I had to implement a new cereal archive type that accepts our own `asio::buffered_write_streamasio::buffered_write_stream` backed stream type.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/catchup/IndexBucketsWork.h [hunk 1]
```diff
@@ -21,6 +21,7 @@ class IndexBucketsWork : public Work
         std::shared_ptr<Bucket> mBucket;
         std::unique_ptr<BucketIndex const> mIndex;
         bool mDone{false};
+        bool mFailed{false};
```
Comment (marta-lokhova) [inline src/catchup/IndexBucketsWork.h:24]: nit: use one BasicWork::State variable to convey final state instead of mDone and mFailed. Also it needs to be reset in doReset (right now this works because we override the retry policy, but it's a footgun)

**Review by marta-lokhova — COMMENTED** [review]
thanks! one small comment, otherwise lgtm

**Review by marta-lokhova — APPROVED** [review]
