### PR TITLE
Fix race on startup with HTTP server

### LINKED ISSUE #5099: 'tx' HTTP endpoint races with startup
core HTTP server starts before we fully load LCL state, which crashes core if `tx` endpoint is called. This also means that all other endpoints may race with core on startup. We should start HTTP server once LCL is done loading.

### PR DESCRIPTION
**Pull request by SirTyson**
# Description

Resolves #5099

This PR adds a check to HTTP endpoints and exits early if core is not in the correct state to service the endpoint. I've audited the endpoints and divided them into three categories:

- Ledger State Dependent Endpoints (i.e. anything with a LedgerHeader or BucketList dependency). Here, we check that LedgerManager is not in `LM_BOOTING_STATE` such that there is some valid LCL state to query. These endpoints include:
   - /tx
   - /sorobaninfo
   - /upgrades
   - /dumpproposedsettings
   - /self-check
   - /maintenance
   - /getledgerentryraw
   - /getledgerentry
   - /info
  
- Herder Dependent Endpoints. These don't need ledger state, but require overlay and herder to be initialized:
   - /peers
   - /connect
   - /droppeer
   - /bans
   - /unban
   - /quorum
   - /scp
   - /stopsurvey
   - /getsurveyresult
   - /startsurveycollecting
   - /stopsurveycollecting
   - /surveytopologytimesliced

- No dependencies. These include all test-only endpoints for simplicity, as well as diagnostic info that should probably always be live, such as /metrics and /ll.

I thought about just delaying starting the endpoint (like the comment initially mentioned), but given the current length of our startup time, we need endpoints like /metrics available at a minimum. It is also probably better from a consumer view for captive-core to reply with a "not ready" status instead of less graceful errors.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/main/QueryServer.cpp [hunk 1]
```diff
@@ -78,22 +78,22 @@ QueryServer::QueryServer(std::string const& address, unsigned short port,
 #ifdef BUILD_TESTS
     if (useMainThreadForTesting)
     {
-        mBucketListSnapshots[std::this_thread::get_id()] =
-            bucketSnapshotManager.copySearchableLiveBucketListSnapshot();
+        auto [live, hotArchive] =
```
Comment (marta-lokhova) [inline src/main/QueryServer.cpp:81]: just curious - what's the motivation behind this specific change?

**Comment by marta-lokhova** [comment]
apologies for reviewing late; for this type of bug (which sadly it's not the first time we're running into), I'd love us to think about a robust solution of type do-it-once-and-forget. Right now we have to update every HTTP endpoint, so I worry whoever is adding a new HTTP endpoint later is going to forget to add the guard (I totally would). We also depend on the exact booting sequence - e.g. ideally CommandHandler doesn't care about the state of Herder - that sequence can change anyway (and it has in the past).

Maybe we can do something simpler?
- add a bool to CommandHandler, mIsReady=false. Add setReady method to be called by LM when state is loaded. 
- in safeRouter, always check if mIsReady is set, and either proceed by calling regular functions, or return some generic "core is booting". 

This is assuming consumers actually care about if the endpoint is reachable. To my knowledge, many search for things like "Synced!" in the `info` result, so from their point-of-view, core won't be up anyway.

**Comment by SirTyson** [comment]
> apologies for reviewing late; for this type of bug (which sadly it's not the first time we're running into), I'd love us to think 
> * add a bool to CommandHandler, mIsReady=false. Add setReady method to be called by LM when state is loaded.
> * in safeRouter, always check if mIsReady is set, and either proceed by calling regular functions, or return some generic "core is booting".
> 
> This is assuming consumers actually care about if the endpoint is reachable. To my knowledge, many search for things like "Synced!" in the `info` result, so from their point-of-view, core won't be up anyway.

I thought about that, but the issue is we don't want all endpoint to be blanketed "not available."  For example, logs and metrics should be available during the "not ready" phase, as it's pretty long (this includes compiling, in-memory state initialization, etc), and during that time we do emit useful logs and metrics. For example, if there was some issue where in-memory state or compilation took a long time and we used a blanket "is ready" flag, we'd have no logs and no metrics from the node at all.

File: src/main/QueryServer.cpp (hunk 1 above)
Comment (SirTyson) [reply src/main/QueryServer.cpp:81]: There's a race condition, where the live and archive snapshot for a thread can be from different LCLs since we acquire and release the lock when copying each snapshot. This doesn't matter in practice since we always update our snapshots atomically per-query later on, but it still seems like a bad and potentially footgunny state.

File: src/main/ApplicationImpl.cpp [hunk 2]
```diff
@@ -807,6 +807,9 @@ ApplicationImpl::start()
 
     mLedgerManager->loadLastKnownLedger();
 
+    // LCL is now loaded; unblock HTTP endpoints that were gated during boot.
+    mCommandHandler->setReady();
```
Comment (marta-lokhova) [inline src/main/ApplicationImpl.cpp:811]: Could we please add a quick test to repro the original issue and confirm the fix works?

Comment (SirTyson) [reply src/main/ApplicationImpl.cpp:811]: Done

Comment (marta-lokhova) [reply src/main/ApplicationImpl.cpp:811]: thanks!
