### PR TITLE
Work shouldn't be scheduled once WorkScheduler is done

### LINKED ISSUE #3106: Crash on shutdown while performing maintenance
Needs to be investigated. The crash occurred when stellar-core was restarted (as part of v17.2.0rc2 -> v.17.2.0 upgrade):
```
2021-06-30T00:03:36.491 GCW5Q [Tx INFO] applying ledger 223875 (txs:2, ops:6)
2021-06-30T00:03:36.505 GCW5Q [Ledger INFO] Closed ledger: [seq=223875, hash=5231b0]
2021-06-30T00:03:40.193 GCW5Q [default INFO] got signal 15, shutting down
2021-06-30T00:03:40.526 GCW5Q [default INFO] Performing maintenance
2021-06-30T00:03:40.526 GCW5Q [History INFO] Trimming history <= ledger 150920 (rmin=150920, qmin=223875, lmin=223811)
2021-06-30T00:03:41.405 GBH7K [default INFO] Starting stellar-core stellar-core 17.2.0 (e47d483433ce4f7eaf0a0512e2556beb482c8851)
2021-06-30T00:03:41.407 GBH7K [Database INFO] Connecting to: postgresql://dbname=stellar user=stellar password=******** host=/var/run/postgresql
2021-06-30T00:03:41.412 GBH7K [SCP INFO] LocalNode::LocalNode@GBH7K qSet: 59d361
2021-06-30T00:03:41.414 GBH7K [Database INFO] DB schema is in current version
```

Note that maintenance ran _after_ core received the shutdown signal, so there might be an issue related to object lifetime during shutdown

### PR DESCRIPTION
**Pull request by hidenori-shinohara**
# Description

Resolves #3106. This issue says that the application crashed after `got signal 15, shutting down`. The stack trace posted there shows that the crash happened because the work class had children when `~Work()` was called.

Explanation of the change in this PR: The `WorkScheduler` class refuses to schedule any work when it's aborting, which makes sense. But there's a small window of time after `shutdownWorkScheduler()` has been called and before the program terminates. During that time window, `mState = ABORTED` and thus `WorkScheduler` continues to schedule new works. This would lead to a crash since the destructor `~Work()` asserts`!hasChildren()` which fails if `WorkScheduler` has scheduled new works. This PR makes sure that `WorkScheduler` won't schedule anything as long as `isAborting()` _or_ `isDone()`.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/work/WorkScheduler.h [hunk 1]
```diff
@@ -47,7 +47,7 @@ class WorkScheduler : public Work
     std::shared_ptr<T>
     scheduleWork(Args&&... args)
     {
-        if (isAborting())
+        if (isAborting() || isDone())
```
Comment (marta-lokhova) [inline src/work/WorkScheduler.h:50]: I agree that we should do this. I also think that for this specific issue it is safer if we do not trigger `scheduleSelfCheck` at all during shutdown. Right now we still execute the code in `scheduleSelfCheck`, so this creates a possibility that we invoke functions on objects that are already shutdown, which would be illegal. 

So I think we also need to cancel mSelfCheckTimer in ApplicationImpl::gracefulStop

Comment (hidenori-shinohara) [reply src/work/WorkScheduler.h:50]: Makes sense! Updated it.

```
^C2021-08-09T17:22:04.913 GBAMW [default INFO] got signal 2, shutting down
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Shutting down: wait-for-lcl
2021-08-09T17:22:04.913 GBAMW [Work DEBUG] work wait-for-lcl : WORK_WAITING -> WORK_ABORTING
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Shutting down: self-check
2021-08-09T17:22:04.913 GBAMW [Work DEBUG] work self-check : WORK_WAITING -> WORK_ABORTING
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Shutting down: work-scheduler
2021-08-09T17:22:04.913 GBAMW [Work DEBUG] work work-scheduler : WORK_WAITING -> WORK_ABORTING
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Abort progress for wait-for-lcl: done
2021-08-09T17:22:04.913 GBAMW [Work TRACE] resetting wait-for-lcl
2021-08-09T17:22:04.913 GBAMW [Work DEBUG] work wait-for-lcl : WORK_ABORTING -> WORK_ABORTED
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Abort progress for self-check: still aborting
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Abort progress for work-scheduler: still aborting
2021-08-09T17:22:04.913 GBAMW [Work TRACE] work-scheduler: waiting for children to abort.
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Abort progress for work-scheduler: still aborting
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Abort progress for self-check: done
2021-08-09T17:22:04.913 GBAMW [Work TRACE] resetting self-check
2021-08-09T17:22:04.913 GBAMW [Work DEBUG] work self-check : WORK_ABORTING -> WORK_ABORTED <---- self-check aborted
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Abort progress for work-scheduler: still aborting
2021-08-09T17:22:04.913 GBAMW [Work TRACE] work-scheduler: waiting for children to abort.
2021-08-09T17:22:04.913 GBAMW [Work TRACE] Abort progress for work-scheduler: done
2021-08-09T17:22:04.913 GBAMW [Work TRACE] resetting work-scheduler
2021-08-09T17:22:04.913 GBAMW [Work DEBUG] work work-scheduler : WORK_ABORTING -> WORK_ABORTED
2021-08-09T17:22:04.913 GBAMW [Bucket TRACE] b72bc26d469a3f5079510767e2ea4773e02da574dec72e2f32f5828b79e0af40 referenced by bucket list
2021-08-09T17:22:04.913 GBAMW [Bucket TRACE] 0000000000000000000000000000000000000000000000000000000000000000 referenced by bucket list
2021-08-09T17:22:05.914 GBAMW [default INFO] Application destructing
2021-08-09T17:22:05.914 GBAMW [Bucket WARNING] BucketManager: shutdown is called more than once
2021-08-09T17:22:05.914 GBAMW [default DEBUG] Joining 11 worker threads
2021-08-09T17:22:05.914 GBAMW [default DEBUG] Joined all 11 threads
2021-08-09T17:22:05.914 GBAMW [default INFO] Application destroyed
2021-08-09T17:22:05.915 GBAMW [default DEBUG] TmpDir deleted: buckets/tmp/process-ed4282c355736d14
2021-08-09T17:22:05.915 GBAMW [default DEBUG] TmpDir deleted: buckets/tmp/history-82fdf5d4107e39e6
2021-08-09T17:22:05.915 GBAMW [default DEBUG] TmpDirManager cleaning: buckets/tmp
```

After `self-check` is aborted above, the log indicates that it didn't even try to schedule anything. As a comparison, without this PR, it would print something like

```
2021-08-06T15:14:12.909 GDH22 [Work TRACE] Starting self-check
2021-08-06T15:14:12.909 GDH22 [Work TRACE] resetting self-check
2021-08-06T15:14:12.909 GDH22 [Work DEBUG] work self-check : WORK_PENDING -> WORK_RUNNING 
```
after it has been aborted.

**Review by marta-lokhova — APPROVED** [review]

**Comment by marta-lokhova** [comment]
r+ 66d09dbdae229900cc046603f43998e6c8438d70
