### PR TITLE
Bucketlist db invariant

### LINKED ISSUE #4368: BucketListIsConsistentWithDatabase broken with BucketListDB
`BucketListIsConsistentWithDatabase` does not currently work with BucketListDB. Note that the invariant is not violated, but the logic to check the invariant itself is not compatible with BucketListDB.

### PR DESCRIPTION
**Pull request by SirTyson**
# Description

Resolves #4368

Fixes `BucketListIsConsistentWithDatabase` when BucketListDB is enabled.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/invariant/BucketListIsConsistentWithDatabase.cpp [hunk 1]
```diff
@@ -258,6 +259,96 @@ BucketListIsConsistentWithDatabase::checkEntireBucketlist()
...
+                }
+            }
+        }
+    }
+
+    auto range =
+        LedgerRange::inclusive(LedgerManager::GENESIS_LEDGER_SEQ, newestLedger);
+
+    // SQL only stores offers when BucketListDB is enabled
+    return counts.checkDbEntryCounts(
```
Comment (dmkozh) [inline src/invariant/BucketListIsConsistentWithDatabase.cpp:348]: I'm not sure if that matters much, but could that check go to `checkOnBucketApply`? It seems like that would be a bit more consistent.

Comment (SirTyson) [reply src/invariant/BucketListIsConsistentWithDatabase.cpp:348]: No, this check makes sure the number of entries in SQL DB matches the number of entries in the BucketList. This is not possible to check on a per-bucket level when applying buckets in-order. For example, suppose an offer `DEADENTRY` exists on level 0, and a `LIVEENTRY` of the same key exists on level 1. The database correctly does not contain the entry such that the offer count is 0. When performing the check on the level 1 bucket, the invariant would fail, as based on that individual bucket, the offer count should be 1 instead of 0.

Essentially we can only do individual Bucket level checks in `checkOnBucketApply`, whereas `checkAfterAssumeState` performs BucketList level checks.

Comment (dmkozh) [reply src/invariant/BucketListIsConsistentWithDatabase.cpp:348]: Thanks for the explanation.

**Review by dmkozh — APPROVED** [review]
