### PR TITLE
History info

### LINKED ISSUE #1377: Add a way to diagnose history archive issues
# Issue type
 * improvement

# Version found
  * all versions

# Issue description
 * When history archive is misconfigured there is no information about that in stellar-core.

## Expected result
* When stellar-core is unable to get or put files from/to history archive for a long time an information in info endpoint should be displayed about that (under status field), like: "Archive 'xyz' seem to not work for uploading/downloading history. Please check permissions/command/something" (wording TBD).

### PR DESCRIPTION
**Pull request by vogel**
Fixes #1377

### CODE REVIEW

File: src/history/HistoryArchiveMonitor.cpp [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+{
+    mHistoryArchiveMonitorData[archiveName].mFailureCount++;
+}
+
+Json::Value
+HistoryArchiveMonitor::getJsonInfo() const
+{
+    auto info = Json::Value{};
+
+    for (auto i : mHistoryArchiveMonitorData)
```
Comment (MonsieurNicolas) [inline src/history/HistoryArchiveMonitor.cpp]: `auto& i` (otherwise I think all you're doing is modifying temp variables?)

File: src/history/HistoryArchiveMonitor.cpp [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+    {
+        auto& archiveInfo = info[i.first];
+        archiveInfo["succeeses"] = i.second.mSuccessCount;
```
Comment (MonsieurNicolas) [inline src/history/HistoryArchiveMonitor.cpp]: just call them `success` and `failure` (plural is `successes` btw)

File: src/main/ApplicationImpl.cpp [hunk 3]
```diff
@@ -112,6 +113,7 @@ ApplicationImpl::initialize()
     mHerderPersistence = HerderPersistence::create(*this);
     mBucketManager = BucketManager::create(*this);
     mCatchupManager = CatchupManager::create(*this);
+    mHistoryArchiveMonitor = make_unique<HistoryArchiveMonitor>();
```
Comment (MonsieurNicolas) [inline src/main/ApplicationImpl.cpp]: Looks to me that `mHistoryArchiveMonitor`  should live under `HistoryManager` and not as a child of the application as history archives are an implementation detail of how history works

File: src/historywork/GetRemoteFileWork.cpp [hunk 4]
```diff
@@ -30,19 +31,36 @@ GetRemoteFileWork::~GetRemoteFileWork()
...
 void
 GetRemoteFileWork::onReset()
 {
     std::remove(mLocal.c_str());
 }
+
+Work::State
+GetRemoteFileWork::onSuccess()
+{
+    mApp.getHistoryArchiveMonitor().markOperationSucceeded(
```
Comment (MonsieurNicolas) [inline src/historywork/GetRemoteFileWork.cpp]: pattern is a bit weird: why not have those metrics attached directly to the `HistoryArchive` object instead of having to expose the ownership to the `*Work` classes? It seems that they are important enough to be first classes into that object.

Then I can just call `mCurrentArchive.recordFailure()`.

File: src/herder/Herder.h [hunk 5]
```diff
@@ -141,8 +141,8 @@ class Herder
     {
     }
 
-    virtual void dumpInfo(Json::Value& ret, size_t limit) = 0;
-    virtual void dumpQuorumInfo(Json::Value& ret, NodeID const& id,
-                                bool summary, uint64 index = 0) = 0;
+    virtual Json::Value getJsonInfo(size_t limit) = 0;
```
Comment (MonsieurNicolas) [inline src/herder/Herder.h]: I am not sure about this change: `Json::Value` doesn't have a move constructor, so standardizing on this pattern doesn't seem that much better

File: src/historywork/GetRemoteFileWork.cpp (hunk 4 above)
Comment (vogel) [reply src/historywork/GetRemoteFileWork.cpp]: I made this only because HistoryArchive classes live in Config. I do not think that having mutable objects inside Config is a good idea. I'll try to find a better place for HistoryArchive objects and then make them mutable.

File: src/herder/Herder.h (hunk 5 above)
Comment (vogel) [reply src/herder/Herder.h]: I think that NRVO helps us here (and also fact that those are called by HTTP endpoint which is not used very frequently and does not look like performance critical code path).

File: src/historywork/GetRemoteFileWork.cpp (hunk 4 above)
Comment (MonsieurNicolas) [reply src/historywork/GetRemoteFileWork.cpp]: yeah what we could do is add a new class that represents the history archive instance (that deals with invocation of archive related work, monitoring, etc), that way we start to formalize the interface with archive a little better (later we can implement proper "load balancing" between archives if we have an interface) and maybe rename the existing HistoryArchive as HistoryArchiveConfiguration

**Comment by vogel** [comment]
Updated. I did a full rebase instead of incremental commits as this is almost 100% different than previous version.

**Comment by vogel** [comment]
Fixed compilation issue

**Comment by vogel** [comment]
r+ 91f2499ca043eab969766cb9f9a193ea14e6b800

**Comment by vogel** [comment]
r+ bd4dd2433daf959cc7ee172653e281b3f2847852

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by spillane85** [comment]
Jed McCaleb my name is Matthew Spillane... I am a big believer maybe the
biggest the only one I feel around me in my circle who are all going to go
to hell for not listening... Now like you said someone's credibility your
word is everything your word is your bond.
 I'm not the typical consumer who can afford to drop a $500 and be part of
your scholarship program due to the financial crisis that is happening
currently United States of America or better yet the world who are
currently making big moves to move forward as we move backward... Itsfunneh
how this whole Trail I've been on since November last year when I found
Stellar lumens for $0.01 the kind of things I've been seeing happen... The
unthinkable like World War 3 Like A Man Named John Rickards explaining to
you how Saudi Arabia will sell all his oil at a high demand and then invest
in the pier solar because the whole energy grid the landlines the pyramids
Antarctica where do you want me to start it's all coming to a head.. that
would make every religion to date nearly at least Christians and Catholics
AKA where the money is at a mere story.. from my understanding I'm watching
Mark Zuckerberg someone who has as much money as Bill Gates who founded the
whole internet not one website but yet major major hacking of people's
identities is taking place like Edward Snowden why do you think they want
him dead.. and then I see a video from George Bush Junior not senior senior
already said A New World Order watch that video what are shaking hands with
Osama bin Laden Laugh Out Loud come on then Junior comes into office and
says listen you either with us or you're a terrorist which then begs me to
question myself now and my moralities as if am i a terrorist and don't even
know it???? 2 billion users trusted Facebook with their privacy but once
it's on the web it can't be taken off just like crypto just like
Ledger's... It's the point of a ledger since 1920s people have little black
books and ledgers in handwriting to keep track but now IBM made a quantum
computer that doesn't talk in binary computer language which is very
dangerous which could actually Wipeout crypto completely cuz crypto may not
be the way to go and that's not what you're offering I understand that...
You were all about it yourself though don't forget... I'm watching United
States Congress tear Mark Zuckerberg a new a******because I realized have
you not noticed the internet is hacked.... It's all through your Google
through another secure email to get onto the web since when???? The world I
understand it.. I understand I'm awake kid I understand I'm a nobody as far
as anyone is concerned but in my ancestry look up the Irish Gaelic meaning
of Spillane and it means to be Chief f****** Grim Reaper Warrior the word
Spillane translation Gaelic Irish formal language of the past to a scythe..
I find that a little strange.. I know I'm related to Mickey Spillane from
New York look them up Hell's Kitchen mobster the last of the gentlemen
gangsters is what he was known as... Tupac Michael Jackson Dave Chappelle
the list goes on.. Jim Carrey now finally a white guy which actually means
a lot... I understand that a stranger can help you succeed in life even
more so than close friends or family... I feel every step forward I take I
take two steps back due to the things you're describing to me or to the
average American.. I understand it's every man for himself I understand
that as well.... I know you're not trying to brag you don't even want to
show your money, you think I'm some kind of moron, there's a thing called
taxes lol hahahaha. I have so much on my mind and so much stress just by
watching the world unfold and no one doing anything about it and I'm not in
a position to at the moment like the rest of us... I'm not trying to brag
but Mark Zuckerberg has 178 billion dollars two billion users and a hell of
a lot of private information... Like I said encrypted through encrypted
through encrypted 2fa Google Authenticator a bunch of crooks.. now I'm
sorry for being very blunt but I've never met you and I do not have the
means and I wish I did I wish I could meet you because the stuff you are
talking about sounds similar to my beliefs being ahead of the Curve being
able to read people and situations and how the people around you will drag
you down... I'm 32 years old white male from Willow Grove Pennsylvania..
this is my email account that I guess I trust Google with... If you are
what you say you are you will maybe send me a more private message not the
same one that goes out to 50 million Americans telling them what I already
know and how every sign up nets you enough to buy your Lamborghini so
excuse me for not being in a position to take part no matter how much I
want to... I can read you is that not good enough and I never met you don't
really know much about you but there's a reason why I'm able to communicate
with you because I did my own digging and just as you found me I found
you... Except I didn't do it through Edward Snowden tactics I did it
through being perceptive the exact meaning of Illuminati to illuminate the
exact meaning of the devil the bringer of light Lucifer the exact meaning
of everything I think I got a good grasp but they are all theories,,,until
it happens...!!!!!!! Dun,dun, dun... I am white good looking young male and
I am oppressed, very intelligent and I am oppressed, why is that????? I
know the answer don't worry a lot of people don't know a lot of people can
throw their money at you I'm not one of them but I would like to at least
hear back, please, or just ignore the world in life and be the little
nobody that's you always be as well.. it makes no difference if you have a
Lamborghini and I got a Lexus... Happiness is not materialistic.. it
definitely sure helps I would never say that it doesn't but things are the
way they are right until someone tries to change them and they die... Any
of this sounds wrong then don't even bother email me back, because I am the
most loyal dog in the yard and I don't want to be part of someone's Union
if it will remain a f*****-up corrupt Enterprise.
. I'm out of time just say I keep hearing on CNBC they're talkin to
billionaire Mark Zuckerberg tell her I am okay sorry out of time on that
question lol  what is time?? I know about BC and AD Missing Years what not
but now I'm out of so-called time... When I was 17 years old I went to the
Navy recruiter office and then I took my official ASVAB test not practice
and scored an 89% the national average is somewhere around 30 something..
it means when I was 17 years old a child I pretty much who's better than 9
out of 10 people round up the 89 percentile to 90... Just like you say, I
say, the right way to go is to surround yourself with people with goals
like yourself people as smart as yourself people like yourself too then
have a Army of educated well off people not just a single person who's
trying to outsmart the situation who was being successful at doing it
that's great for you, I'm watching Zuckerberg get his ass kicked about a
stupid f****** website he created as a sophomore in college based off of a
movie that he saw claiming their not connected and he now has 2 billion
followers and a lot of private information and of course they want the
information he has.. he did the government just said save your s***we're
about to overreact we don't want that to happen I suggest you go home
review everything and come back because they're out of time once again what
is time when the world is at stake, nothing but a mere facade.. 200 billion
dollars and he cannot go against these m************ Global Elite, that our
own nation is part of conspiracies that are mainly true they want to write
him today for all his private information on Americans they wanted to kill
Snowden for what he did.. but once again all a facade and ain't that like
the name of the guy in Syria al-farouq Asad Asad
.. hmmmm.... I should be speaking out not to you but to the public maybe
through videos like you did why was there a shootout at YouTube this week
but when Charlie hebdo in France got shot up a little tiny newspaper
company in this world for one little tiny cartoon of the Muslim Prophet
Muhammad it was World Wide News... I get the picture, this world is
f*****and I don't want to be on that side, do you hear me or not.????
That's why this thing called time is running out because it's all hitting
the fan I understand that I'm just not someone whose well off wealthy, but
I have something more dangerous, a wealth of intelligence.... I believe in
destiny..
 Everyone's time will come once again talk of time right braid the
holographic Universe a book written read Behold a Pale Horse it's called
you know silent Wars to control populations control the prices of Maine
good like coffee sugar bread milk gas also the elite can live large
everyone else is f*****read the lost city of Atlantis now they're trying to
read replicated and right now in Saudi Arabia, at least that's today's plan
for the future but who knows.. the Russians are involved with Syria arming
them and we're about to go to war with them you will see just to make oil
prices rise just so they can sell out and say haha we have new technology
where we don't need that look at Tesla look at you Elon Musk.. Meijer
standing is at every device around is picking up everything just like in
Fast & Furious after Paul Walker died the god tool or whatever was God's
eye shits real.. Amazon Alexa is indicting people, a f****** pacemaker and
a man's heart and indicted him because somehow they were able to go back in
time and check his heart rhythm during the story Alibi he gave and it does
not corroborate with this patterns of his heart and distress and whatnot
come on now.. hahahaha.. what do you think on a personal level this is my
email address I'm sure you know a lot more than I even do because I'm sure
you're already putting it to use as you are,, everyone every company has
access to people and what their likes are so then they can throw it in
front of them is this all your whole teaching is this your scholarship as
you call it.. at least no like I said I am a friend I can be trusted why
don't you background search me Matthew Christopher Spillane 32
Pennsylvania,, and you'll see how I've been screwed by the system and I'm
fed up... That's the whole problem trust trust trust trust trust... I'm
done for real this time you know how to find me like you did before I'm not
sure I haven't dug up anything actually how to find your personal s*** I
just know your little advertisement will get this message what will be done
about it I don't know I don't know who it will be intercepted by and
deleted by thrown in trash you'll never hear it who knows... But I will
continue ranting and raving to the world real soon if I can't get a goddamn
resolution.. thank you for your "time".. matthewspillane85@gmail.com



Matthew Spillane

**Comment by MonsieurNicolas** [comment]
ran into #1635

**Comment by MonsieurNicolas** [comment]
@latobarita: retry
