### PR TITLE
Trustline, offers, issuers fixes and changes

### LINKED ISSUE #776: It should be possible to delete offers even when one of the related trust line is deleted
Right now the code just throws

### LINKED ISSUE #777: Offers should be considered invalid (and deleted) when any of the related trustlines is deleted
Right now it just throws, blocking the offer exchange from making progress

### LINKED ISSUE #778: It should be possible to delete issuers even if they issued credits
When an issuer does not exist, we should ensure that it's still possible to delete trust lines (for the defunct credits issued by the issuer)

### LINKED ISSUE #782: add a flag to make "auth" flags read-only
This allows an issuer to be explicit when it comes to "immutability" of the contract that they provide (non revocable auth in particular).

Such accounts become non-mergeable (as merging would allow to indirectly clear flags).

This also allows to remove an index on trust lines (performance)

### LINKED ISSUE #783: Rationalize the code base when it comes to issuers existance
In some places, we check for the issuer's existence before performing operations, in some other, we don't.

We should always check for existence, as credits with no issuers are basically defunct (and a vector for people getting defrauded).

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
Sorry for the churn on the protocol side @nullstyle (review the issues for more detail)

This PR addresses a few issues related to how we handle offers, trust lines and issuers as objects get deleted or mutated in the ledger.

Highlights:
 * Make it possible to delete offers that don't have valid trustlines, resolves #776 
 * Ensure that offers with invalid trustlines get deleted, resolves #777 
 * Allow issuers to be merged, resolves #778 
 * Rationalized the code base wrt non existent issuers (payment, changetrust, manageoffer), resolves #783
 * Added a new flag for issuers to mark their account as "immutable" (from an auth point of view), resolves #782 

Note: some of this could be avoided by implementing some sort of cascading effects on the ledger. Like delete an issuer -> delete related trust lines -> delete related offers. This would potentially cause larger chunks of work in the ledger at once, requires additional indexes (in the case of offer cleanup after payments, quite a bit of extra logic), and has the potential for confusion from the end user point of view.

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
I also included a fix for #773

File: src/ledger/AccountFrame.h [hunk 1]
```diff
@@ -76,6 +76,7 @@ class AccountFrame : public EntryFrame
     bool addNumEntries(int count, LedgerManager const& lm);
 
     bool isAuthRequired() const;
+    bool isStaticAuth() const;
```
Comment (jedmccaleb) [inline src/ledger/AccountFrame.h]: Can you use the same name as the enum so isImmutableAuth.

Comment (MonsieurNicolas) [inline src/ledger/AccountFrame.h]: Forgot to rename this, taking care of it...
