### PR TITLE
fix HistoryManagerImpl::loadBucketsReferencedByPublishQueue

### LINKED ISSUE #1296: Stellar core sometimes dies with "Assertion `snap' failed."
Log message:
stellar-core: bucket/FutureBucket.cpp:267: void stellar::FutureBucket::startMerge(stellar::Application&): Assertion `snap' failed.

### LINKED ISSUE #1518: Some buckets are missing
I have another problem with Stellar Core. After resolving the problems with joining the public network, I was running the node for few days without problems. The start/restart worked flawlessly, the node connected each time to network, but now I encountered another problem. Despite node claiming to be fully synced, it does not see any transaction made. It did for some time as I tested it via Horizon API connected to the node, but now it does not see anything. When I look at the logs I can see:

```
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.334 GBA2J [default INFO] Starting stellar-core v9.0.1-6-g226ba55
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.334 GBA2J [default INFO] Config from /home/xlm/.stellar-core/stellar-core.cfg
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.335 GBA2J [Database INFO] Connecting to: postgresql://dbname=dbname user=user password=******** host=127.0.0.1
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.350 GBA2J [SCP INFO] LocalNode::LocalNode@GBA2J qSet: b3a703
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.350 GBA2J [default INFO] Listening on 127.0.0.1:12059 for HTTP requests
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.352 GBA2J [History INFO] Archive 'local' has 'put' and 'get' commands, will be read and written
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.352 GBA2J [History INFO] Archive 'sdf1' has 'get' command only, will not be written
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.352 GBA2J [History INFO] Archive 'sdf2' has 'get' command only, will not be written
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.352 GBA2J [History INFO] Archive 'sdf3' has 'get' command only, will not be written
Jan 30 12:52:06 localhost stellar-core[11412]: 2018-01-30T12:52:06.353 GBA2J [default INFO] Loading last known ledger
Jan 30 12:52:07 localhost stellar-core[11412]: 2018-01-30T12:52:07.013 GBA2J [Ledger WARNING] Some buckets are missing in '/home/xlm/buckets'.
Jan 30 12:52:07 localhost stellar-core[11412]: 2018-01-30T12:52:07.014 GBA2J [Ledger WARNING] Attempting to recover from the history store.
Jan 30 12:52:07 localhost stellar-core[11412]: 2018-01-30T12:52:07.019 GBA2J [History INFO] Starting RepairMissingBucketsWork
```

After that at some point:

```
stellar-core: bucket/FutureBucket.cpp:267: void stellar::FutureBucket::startMerge(stellar::Application &): Assertion `snap' failed.
Aborted
```

The node then crashes. What's wrong this time? Could the buckets be damaged by running Horizon?

My system specs:

```
Ubuntu 16.04 x64
Stellar-core v9.0.1-6
SSD Hard Drive
Network Connection 100 Mbps
```

Config and SCP problem with resultion: https://github.com/stellar/stellar-core/issues/1487

### PR DESCRIPTION
**Pull request by vogel**
Before fix this implementation would return only one item per bucket
even if it occured in multiple publishqueue items. New implementations
returns one item per bucket per publishqueue item, which is consistent
with how PublishQueueBuckets works in other contexts.

It will stop crashing on assert(snap) now.

Fixes #1296
Fixes #1518

### CODE REVIEW

File: src/bucket/PublishQueueBuckets.h [hunk 1]
```diff
@@ -14,19 +14,23 @@ namespace stellar
 class PublishQueueBuckets
 {
   public:
+    using storage = std::map<std::string, int>;
```
Comment (MonsieurNicolas) [inline src/bucket/PublishQueueBuckets.h]: `storage` typenames start with an uppercase. Why not just calling it `BucketCount` or something like this - `Storage` doesn't really convey anything

File: src/history/HistoryManagerImpl.cpp [hunk 2]
```diff
@@ -566,25 +566,28 @@ HistoryManagerImpl::getPublishQueueStates()
     return states;
 }
 
-std::vector<std::string>
+PublishQueueBuckets::storage
 HistoryManagerImpl::loadBucketsReferencedByPublishQueue()
 {
     auto states = getPublishQueueStates();
-    std::set<std::string> buckets;
+    auto result = PublishQueueBuckets::storage{};
```
Comment (MonsieurNicolas) [inline src/history/HistoryManagerImpl.cpp]: I'd rather see `TypeName result;` than using `auto`

**Comment by MonsieurNicolas** [comment]
r+ 7c622df23073acda976d1e5d862c6c4368db6ed7
