### PR TITLE
fix catchup current/0 error on very up-to-date databases

### LINKED ISSUE #2143: Stellar-core asserts on command-line catchup
## Issue Description

When using command-line catchup like `stellar-core catchup current/0 --conf <config>` it is possible to make stellar-core assert.

## Steps to Reproduce
1. `stellar-core new-db --conf <config>`
2. `stellar-core run --conf <config>`
3. Catch up to the network and wait for stellar-core to close a ledger that is not a checkpoint
4. `stellar-core catchup current/0 --conf <config>`

## Expected Result
Something like
```
2019-06-13T11:23:33.071 GDJIR [default INFO] *
2019-06-13T11:23:33.071 GDJIR [default INFO] * Target ledger 24328466 is not newer than last closed ledger - nothing to do
2019-06-13T11:23:33.071 GDJIR [default INFO] * If you really want to catchup to 24328466 run stellar-core new-db
2019-06-13T11:23:33.071 GDJIR [default INFO] *
``` 

## Actual Result
Something like
```
2019-06-13T11:23:20.638 GBYAG [History INFO] Last closed ledger is later than current checkpoint: 24328466 > 24328447
2019-06-13T11:23:20.638 GBYAG [History INFO] Wait until next checkpoint before retrying
2019-06-13T11:23:20.638 GBYAG [History ERROR] Nothing to catchup to  [CatchupWork.cpp:86]
2019-06-13T11:23:20.638 GBYAG [Ledger ERROR] Error catching up: Invalid argument [LedgerManagerImpl.cpp:650]
2019-06-13T11:23:20.638 GBYAG [Ledger ERROR] Catchup will restart at next close. [LedgerManagerImpl.cpp:651]
2019-06-13T11:23:20.638 GBYAG [Ledger INFO] Changing state LM_CATCHING_UP_STATE -> LM_BOOTING_STATE
Assertion failed: (mCatchupState == CatchupState::APPLYING_HISTORY), function historyCaughtup, file ledger/LedgerManagerImpl.cpp, line 646.
Abort trap: 6
```

### stellar-core Version
v11.1.0-32-g7fd4826c

### Environment
Running on Mac without a container.

### PR DESCRIPTION
**Pull request by vogel**
# Description

Resolves #2143

Fix for edge case when doing command line catchup current/0 on databases that have at least one-past-last-network-checkpoint ledgers.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/catchup/CatchupWork.cpp [hunk 1]
```diff
@@ -221,12 +210,7 @@ CatchupWork::doWork()
     // Step 2: Compare local and remote states
     if (!hasAnyLedgersToCatchupTo())
     {
-        mApp.getCatchupManager().historyCaughtup();
-        asio::error_code ec = std::make_error_code(std::errc::invalid_argument);
-        mProgressHandler(ec, ProgressState::FINISHED,
-                         LedgerHeaderHistoryEntry{},
-                         mCatchupConfiguration.mode());
-        return State::WORK_SUCCESS;
+        return State::WORK_FAILURE;
```
Comment (MonsieurNicolas) [inline src/catchup/CatchupWork.cpp]: why not logging here instead of in `onFailureRaise` ? This is where we have full context (later you have to reverse engineer the failure)

File: src/ledger/LedgerManagerImpl.cpp [hunk 2]
```diff
@@ -648,7 +648,10 @@ LedgerManagerImpl::historyCaughtup(asio::error_code const& ec,
     if (ec)
     {
         CLOG(ERROR, "Ledger") << "Error catching up: " << ec.message();
-        CLOG(ERROR, "Ledger") << "Catchup will restart at next close.";
+        if (ec == std::make_error_code(std::errc::timed_out))
```
Comment (MonsieurNicolas) [inline src/ledger/LedgerManagerImpl.cpp]: This change doesn't make sense to me as it has more to do how `catchup` was invoked:
* this error message should always be ignored when running command line
* this error message should always be displayed when running normally (well it's more complicated than this, but we don't care in the context of this PR)

**Comment by MonsieurNicolas** [comment]
looks good, we'll merge when we reopen master

**Comment by MonsieurNicolas** [comment]
r+ f7fa8e5ec7d346795a117e6cd5501da44476f753
