### PR TITLE
Fix catchup log message when catching up to current

### LINKED ISSUE #2476: Catch-up logging reports "0" when catching up to "current"
## Issue Description
With version 12.5.0rc2, logging during catch-up emits lines of the form "Catching up to ledger <LedgerNumber>". The ledger number is not substituted correctly when using catchup of the form "current/0".

## Steps to Reproduce
Prepare a new database then run `stellar-core catchup current/0 --conf <Config>`

## Expected Result
Log lines should say something like "Catching up to ledger 28819839".

## Actual Result
```
[History INFO] Catching up to ledger 0: downloading and verifying buckets: 1/21 (4%)
```

### PR DESCRIPTION
**Pull request by sisuresh**
# Description

Resolves #2476 

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/catchup/CatchupWork.cpp [hunk 1]
```diff
@@ -53,9 +53,25 @@ CatchupWork::~CatchupWork()
 std::string
 CatchupWork::getStatus() const
 {
-    return fmt::format(
-        "Catching up to ledger {}: {}", mCatchupConfiguration.toLedger(),
-        mCurrentWork ? mCurrentWork->getStatus() : Work::getStatus());
+    std::string toLedger;
+    if (mCatchupConfiguration.toLedger() == CatchupConfiguration::CURRENT)
```
Comment (sisuresh) [inline src/catchup/CatchupWork.cpp]: @jonjove Do you think it's valuable to log the ledger number when catching up to current? We could just log "CURRENT" instead.

Comment (jonjove) [reply src/catchup/CatchupWork.cpp]: It's a good question. I think the answer is yes, because it makes it very explicit. Otherwise you might look back at logs and wonder to what ledger was it actually catching up.

**Comment by MonsieurNicolas** [comment]
r+ 970641534cbdc204e76f829a228460b5443903d9
