### PR TITLE
Replace the trustline native check assert with a non soci exception

### LINKED ISSUE #2889: BulkLoadTrustLinesOperation constructor assert should throw instead
The `BulkLoadTrustLinesOperation` constructor currently asserts that the asset is not native. Instead, it should throw an exception similar to `getTrustLineStrings` when it's called with a native asset.

### PR DESCRIPTION
**Pull request by sisuresh**
# Description

Resolves #2889.

# Checklist
- [ ] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [ ] Rebased on top of master (no merge commits)
- [ ] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [ ] Compiles
- [ ] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by jonjove** [comment]
Looks good to me, @MonsieurNicolas feel free to r+ if you're happy with this change.

File: src/ledger/LedgerTxnTrustLineSQL.cpp [hunk 1]
```diff
@@ -414,7 +414,11 @@ class BulkLoadTrustLinesOperation
         for (auto const& k : keys)
         {
             releaseAssert(k.type() == TRUSTLINE);
-            releaseAssert(k.trustLine().asset.type() != ASSET_TYPE_NATIVE);
+            if (k.trustLine().asset.type() == ASSET_TYPE_NATIVE)
```
Comment (MonsieurNicolas) [inline src/ledger/LedgerTxnTrustLineSQL.cpp:417]: in the other bulk* functions we use `validateTrustLineKey` instead

**Review by MonsieurNicolas — CHANGES_REQUESTED** [review]

File: src/ledger/LedgerTxnTrustLineSQL.cpp (hunk 1 above)
Comment (sisuresh) [reply src/ledger/LedgerTxnTrustLineSQL.cpp:417]: I didn't use `validateTrustLineKey` here because that would technically be a protocol change. For example, we would return an `txINTERNAL_ERROR` when trying to bulk load an invalid asset, which we don't do at the moment.

Comment (MonsieurNicolas) [reply src/ledger/LedgerTxnTrustLineSQL.cpp:417]: we call it already in `LedgerTxnRoot::Impl::loadTrustLine` so right now it's more a footgun that bulk load doesn't have the same invariants than point load

Comment (jonjove) [reply src/ledger/LedgerTxnTrustLineSQL.cpp:417]: So do you propose that @sisuresh should use `validateTrustLineKey` but gate it on protocol version? Otherwise it's a protocol change, because we don't necessarily load everything we prefetch.

Comment (sisuresh) [reply src/ledger/LedgerTxnTrustLineSQL.cpp:417]: So I tried to use `validateTrustLineKey` as a protocol change, but it looks like we can actually "prefetch" the trustline for the issuer in most operations that use trustlines. Ex. https://github.com/stellar/stellar-core/blob/fb2948e02579257433432ffa7aab173ccbd5aaa1/src/transactions/PathPaymentOpFrameBase.cpp#L37

Comment (jonjove) [reply src/ledger/LedgerTxnTrustLineSQL.cpp:417]: @sisuresh Independent of what we decide to do in this thread, please open an issue for us to fix that later.

Comment (MonsieurNicolas) [reply src/ledger/LedgerTxnTrustLineSQL.cpp:417]: agree @jonjove . let's discuss other problems elsewhere

**Comment by MonsieurNicolas** [comment]
r+ 273166d3975e847d090c42edd446d58d3638ef4f
