### PR TITLE
Reset shared_future in FutureBucket when it's ready

### LINKED ISSUE #2298: Some buckets are leaked
Looks like fixing #2286 was not enough, and we still have bucket number constantly fluctuating (with total number of files being over expected 31). Checking the logs, the number of buckets referenced by the bucketlist, publishqueue and LCL is correct, so it must be failing the `refcount == 1` check in `forgetUnreferencedBuckets`

### PR DESCRIPTION
**Pull request by marta-lokhova**
This should resolve #2298 -- some standard library implementations (libstdc++) store task lambdas in the shared state, which we used to keep alive for a while (specifically, until level spill which could take months for low level buckets). This change explicitly resets shared_future once it's done.

The second change is a minor update to catchup, to stop referencing buckets earlier (currently we drop bucket references at the very end of a potentially long CatchupWork)

### CODE REVIEW

**Comment by cocoi241116** [comment]
Oke thanks br

File: src/bucket/FutureBucket.h [hunk 1]
```diff
@@ -59,7 +59,8 @@ class FutureBucket
     std::shared_ptr<Bucket> mInputCurrBucket;
     std::shared_ptr<Bucket> mInputSnapBucket;
     std::vector<std::shared_ptr<Bucket>> mInputShadowBuckets;
-    std::shared_future<std::shared_ptr<Bucket>> mOutputBucket;
+    std::shared_ptr<Bucket> mOutputBucket;
+    std::shared_future<std::shared_ptr<Bucket>> mOutputBucketFuture;
```
Comment (MonsieurNicolas) [inline src/bucket/FutureBucket.h]: no test update?

Comment (marta-lokhova) [reply src/bucket/FutureBucket.h]: We do not test the internals of FutureBucket, only its public interface, which functionally did not change.

File: src/bucket/FutureBucket.cpp [hunk 2]
```diff
@@ -299,7 +315,7 @@ FutureBucket::startMerge(Application& app, uint32_t maxProtocolVersion,
 
     assert(curr);
     assert(snap);
-    assert(!mOutputBucket.valid());
+    assert(!mOutputBucketFuture.valid());
```
[the remark this answers is not in the document]
Comment (marta-lokhova) [reply src/bucket/FutureBucket.cpp]: Good idea, fixed (plus one other small simplification). If the change looks ok, I can squash the commits.

File: src/bucket/FutureBucket.cpp [hunk 3]
```diff
@@ -233,24 +240,29 @@ FutureBucket::resolve()
...
+        // Explicitly reset shared_future to ensure destruction of shared state.
+        // Some compilers store packaged_task lambdas in the shared state,
+        // keeping its captures alive as long as the future is alive.
+        mOutputBucketFuture = std::shared_future<std::shared_ptr<Bucket>>();
     }
 
     if (mOutputBucketHash.empty())
     {
-        mOutputBucketHash = binToHex(bucket->getHash());
+        mOutputBucketHash = binToHex(mOutputBucket->getHash());
```
Comment (MonsieurNicolas) [inline src/bucket/FutureBucket.cpp]: `mOutputBucket` is only set above, right?

So why not setting `mOutputBucketHash` in the same place?
Actually maybe `resolve` should just start with `if (LIVE_OUTPUT) { return mOutputBucket; } ` right now the code is written in an almost idempotent way, which doesn't make much sense

**Comment by MonsieurNicolas** [comment]
r+ d50d4a69b796a1e37c55458521741503972fc432
