### PR TITLE
Fixes protocol upgrade bug in BucketManager test

### LINKED ISSUE #3349: Some bucket tests don't actually perform protocol upgrades
See https://github.com/stellar/stellar-core/pull/3329#discussion_r812222798 for more information.

### PR DESCRIPTION
**Pull request by SirTyson**
# Description

Resolves #3349

Fixes issue in some `BucketManager` tests where the protocol version would not upgrade properly.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/ledger/test/LedgerTestUtils.cpp [hunk 1]
```diff
@@ -535,5 +535,13 @@ generateLedgerHeadersForCheckpoint(
     makeValid(res, firstLedger, state);
     return res;
 }
+
+UpgradeType
```
Comment (SirTyson) [inline src/ledger/test/LedgerTestUtils.cpp:539]: I don't think this really belongs in LedgerTestUtils, but I couldn't see a more logical header to but it in.

File: src/bucket/test/BucketManagerTests.cpp [hunk 2]
```diff
@@ -1242,7 +1243,33 @@ class StopAndRestartBucketMergesTest
             resolveAllMerges(app->getBucketManager().getBucketList());
             auto countersBeforeClose =
                 app->getBucketManager().readMergeCounters();
-            closeLedger(*app);
+
+            if (firstProtocol != secondProtocol &&
```
Comment (marta-lokhova) [inline src/bucket/test/BucketManagerTests.cpp:1247]: I think we don't need this if block, as it doesn't actually impact upgrades past genesis ledger.

File: src/ledger/test/LedgerTestUtils.cpp (hunk 1 above)
Comment (marta-lokhova) [reply src/ledger/test/LedgerTestUtils.cpp:539]: Any reason not to keep it where it used to be?

**Comment by MonsieurNicolas** [comment]
@SirTyson any update on this one?

**Comment by SirTyson** [comment]
> @SirTyson any update on this one?

I don't think any additional updates are required, I believe I addressed Marta's comments.

**Comment by marta-lokhova** [comment]
@SirTyson I don't see any changes, maybe you forgot to push? (there's also a merge conflict that we should resolve)

File: src/ledger/test/LedgerTestUtils.cpp (hunk 1 above)
Comment (SirTyson) [reply src/ledger/test/LedgerTestUtils.cpp:539]: Since several different test files use this function now, I thought it would make more sense to put it in a utils header instead of `TxTest.h`.

File: src/bucket/test/BucketManagerTests.cpp (hunk 2 above)
Comment (marta-lokhova) [reply src/bucket/test/BucketManagerTests.cpp:1247]: oh I see, there's been some renaming, so LEDGER_PROTOCOL_VERSION is the max version supported by core. So yeah, we do need to update it. Why does it need to be here though? I think it'd be cleaner to update it in between application shutdown and start, since this is when the change takes effect.

**Comment by marta-lokhova** [comment]
r+ aa519541374a5737c1aeb7aa46b05c990d681430
