### PR TITLE
Bug 2874 flaky bucketlist invariant test

### LINKED ISSUE #2874: flaky test: "BucketListIsConsistentWithDatabase bucket bounds"
this happened on 8671122b

```
2021-01-09T20:11:53.351 <test> [History INFO] Applying buckets
2021-01-09T20:11:53.354 <test> [Bucket INFO] Apply-rates for 128-entry bucket 3.curr au:32000000 ad:0 tu:26000000 td:0 ou:25000000 od:0 du:24000000 dd:0 cu:21000000 cd:0 T:128000000
2021-01-09T20:11:53.354 <test> [Bucket INFO] Entry-counts for 128-entry bucket 3.curr au:32 ad:0 tu:26 td:0 ou:25 od:0 du:24 dd:0 cu:21 cd:0
2021-01-09T20:11:53.354 <test> [Bucket INFO] Bucket-apply: 128 entries in 22.32KB/69.47KB in 1/7 files (32%)
2021-01-09T20:11:53.361 <test> [Bucket INFO] Apply-rates for 166-entry bucket 2.snap au:20000000 ad:10000000 tu:28000000 td:7000000 ou:27000000 od:9000000 du:32000000 dd:7000000 cu:24000000 cd:2000000 T:166000000
2021-01-09T20:11:53.361 <test> [Bucket INFO] Entry-counts for 166-entry bucket 2.snap au:20 ad:10 tu:28 td:7 ou:27 od:9 du:32 dd:7 cu:24 cd:2
2021-01-09T20:11:53.361 <test> [Bucket INFO] Bucket-apply: 294 entries in 45.57KB/69.47KB in 2/7 files (65%)
2021-01-09T20:11:53.366 <test> [Bucket INFO] Apply-rates for 50-entry bucket 2.curr au:11000000 ad:2000000 tu:7000000 td:5000000 ou:7000000 od:4000000 du:7000000 dd:1000000 cu:5000000 cd:1000000 T:50000000
2021-01-09T20:11:53.366 <test> [Bucket INFO] Entry-counts for 50-entry bucket 2.curr au:11 ad:2 tu:7 td:5 ou:7 od:4 du:7 dd:1 cu:5 cd:1
2021-01-09T20:11:53.366 <test> [Bucket INFO] Bucket-apply: 344 entries in 52.95KB/69.47KB in 3/7 files (76%)
2021-01-09T20:11:53.369 <test> [Bucket INFO] Apply-rates for 54-entry bucket 1.snap au:13000000 ad:0 tu:9000000 td:6000000 ou:5000000 od:1000000 du:5000000 dd:5000000 cu:7000000 cd:3000000 T:54000000
2021-01-09T20:11:53.369 <test> [Bucket INFO] Entry-counts for 54-entry bucket 1.snap au:13 ad:0 tu:9 td:6 ou:5 od:1 du:5 dd:5 cu:7 cd:3
2021-01-09T20:11:53.369 <test> [Bucket INFO] Bucket-apply: 398 entries in 60.47KB/69.47KB in 4/7 files (87%)
2021-01-09T20:11:53.371 <test> [Bucket INFO] Apply-rates for 42-entry bucket 1.curr au:5000000 ad:4000000 tu:10000000 td:3000000 ou:6000000 od:4000000 du:6000000 dd:1000000 cu:3000000 cd:0 T:42000000
2021-01-09T20:11:53.371 <test> [Bucket INFO] Entry-counts for 42-entry bucket 1.curr au:5 ad:4 tu:10 td:3 ou:6 od:4 du:6 dd:1 cu:3 cd:0
2021-01-09T20:11:53.372 <test> [Bucket INFO] Bucket-apply: 440 entries in 65.93KB/69.47KB in 5/7 files (94%)
2021-01-09T20:11:53.374 <test> [Bucket INFO] Apply-rates for 14-entry bucket 0.snap au:1000000 ad:0 tu:0 td:1000000 ou:4000000 od:1000000 du:4000000 dd:2000000 cu:1000000 cd:0 T:14000000
2021-01-09T20:11:53.374 <test> [Bucket INFO] Entry-counts for 14-entry bucket 0.snap au:1 ad:0 tu:0 td:1 ou:4 od:1 du:4 dd:2 cu:1 cd:0
2021-01-09T20:11:53.374 <test> [Bucket INFO] Bucket-apply: 454 entries in 67.72KB/69.47KB in 6/7 files (97%)
2021-01-09T20:11:53.375 <test> [Bucket INFO] Apply-rates for 14-entry bucket 0.curr au:1000000 ad:1000000 tu:2000000 td:0 ou:1000000 od:3000000 du:4000000 dd:0 cu:2000000 cd:0 T:14000000
2021-01-09T20:11:53.375 <test> [Bucket INFO] Entry-counts for 14-entry bucket 0.curr au:1 ad:1 tu:2 td:0 ou:1 od:3 du:4 dd:0 cu:2 cd:0
2021-01-09T20:11:53.375 <test> [Bucket INFO] Bucket-apply: 468 entries in 69.47KB/69.47KB in 7/7 files (100%)
2021-01-09T20:11:53.376 <test> [History INFO] ApplyBuckets : done, restarting merges
<Expression success="false" type="REQUIRE_THROWS_AS" filename="invariant/test/BucketListIsConsistentWithDatabaseTests.cpp" line="722">
        <Original>
          blg.applyBuckets(), InvariantDoesNotHold
        </Original>
        <Expanded>
          blg.applyBuckets(), InvariantDoesNotHold
        </Expanded>
      </Expression>2021-01-09T20:11:53.377 <test> [default INFO] Application destructing
```

### PR DESCRIPTION
**Pull request by graydon**
# Description

Resolves #2874

There are two things going on in 2874, this PR fixes both of them (and does a little auxiliary improvement along the way):

First: the (sometimes) failing test checks that an invariant detects a type of malformed `LIVEENTRY` the test generates and applies from a bucket; but this invariant did not _always_ detect that type of `LIVEENTRY` because _sometimes_ (due to some nondeterminism) the test would also produce a `DEADENTRY` that annihilated the malformed `LIVEENTRY` during a merge before it was detected by the invariant. So the main fix is the last commit, to just "not make `DEADENTRY`s in the test anymore". This causes the `LIVEENTRY`s to always make it through to the point where they're detected by the test, so the test will always pass.

Second: the test was failing _nondeterministically_ because it stored live and dead `LedgerKey`s in a hashtable (and decided which entries to kill by selecting entries by hashtable order) and the _entire infrastructure_ of hashing using `shortHash::*` was just .. always nondeterministic: it had never been retrofit to key its hash with seeded-pseudorandom data  during tests, at all. So this change fixes that: the key material used in `shortHash` is now seeded along with all the other seedable PRNGs from the test seed, when testing. This is the middle commit.

Finally: a few other sources of nondeterminism-in-testing-that-should-be-deterministic were fixed while investigating. This is the first commit, and while it doesn't change the determinism of the test passing or failing, it does change its output at high trace levels (and the contents of buckets). So I included it as cleanup.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] N/A If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/crypto/ShortHash.cpp [hunk 1]
```diff
@@ -3,31 +3,66 @@
...
+#include <mutex>
 #include <sodium.h>
 
 namespace stellar
 {
 namespace shortHash
 {
-static unsigned char sKey[crypto_shorthash_KEYBYTES];
+static unsigned char gKey[crypto_shorthash_KEYBYTES];
+static std::mutex gKeyMutex;
```
Comment (jonjove) [inline src/crypto/ShortHash.cpp:15]: I'm not 100% sure how I feel about this. We were previously treating this as initialization is not thread safe, and therefore there wasn't any locking overhead during normal operation. I don't have a good feeling for how big the impact of this will be. I don't know what the alternatives are. Thoughts?

**Review by jonjove — COMMENTED** [review]
Looks fine to me, other than one performance related question about the shorthash change.

File: src/crypto/ShortHash.cpp (hunk 1 above)
Comment (graydon) [reply src/crypto/ShortHash.cpp:15]: I just tested this: cranked the `[shorthash]` test iteration count up to 100000. Even then, `perf(1)` isn't capable of measuring non-noise differences in time (it actually seems to think the mutex version goes _faster_, but it's well within noise) and the instruction count difference is 11711107277 insns without mutex, 11712128476 with mutex (i.e. 0.00008x more instructions executed, on a test that does nothing but call shorthash in a loop).

I guess non-contended mutex acquire is fairly fast these days!

**Comment by MonsieurNicolas** [comment]
r+ 41fb5790f4bf5e40ee67fd89406054a9f4cb4127
