### PR TITLE
Fix noisy eviction scan warnings

### LINKED ISSUE #4208: Incomplete Bucket Scan metric is too noisy

### PR DESCRIPTION
**Pull request by SirTyson**
# Description

Resolves #4208

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/bucket/BucketList.cpp [hunk 1]
```diff
@@ -891,14 +891,11 @@ BucketList::scanForEviction(Application& app, AbstractLedgerTxn& ltx,
...
+        // an update. To prevent noisy warnings, we assume we have the entire
+        // period to scan the bucket.
         auto period = bucketUpdatePeriod(evictionIter.bucketListLevel,
                                          evictionIter.isCurrBucket);
-
-        // Ledgers remaining until the current Bucket changes
-        auto ledgersRemainingToScanBucket = period - (ledgerSeq % period);
-        auto bytesRemaining = b->getSize() - evictionIter.bucketFileOffset;
-        if (ledgersRemainingToScanBucket * scanSize < bytesRemaining)
+        if (period * scanSize < b->getSize())
```
Comment (marta-lokhova) [inline src/bucket/BucketList.cpp:898]: while we're here, could add some more info to the log below? (maybe bucket level + hash?)

**Comment by marta-lokhova** [comment]
r+ 66d36896df657a727d5c5ec6d15f18ac36d618a6
