### PR TITLE
bug 2128: resolve any ready futures before queueing publish state.

### LINKED ISSUE #2128: Merges take longer to complete over time
## Summary

Looks like over time merges are taking longer.

Observed on nodes that watch pubnet *and* publish.

### Kernel
Linux 3.13.0-139-generic #188-Ubuntu SMP Tue Jan 9 14:43:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### SKU
AWS m3.large

vCPUs: 2
model name      : Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz

RAM: 8GB

Drive: EBS

## Description of the problem

As a point of comparison, here is how CPU utilization normally looks like:
image

but after a few days, it degrades into:
image

Restarting the machine causes the merges to complete fast again (here is a graph showing both right before and after a restart):
image

### Potential root cause

It looks like `vruntime` is very high for those threads, expected as all they do is compute `SHA256`.

According to https://www.kernel.org/doc/Documentation/scheduler/sched-design-CFS.txt processes are sorted by `vruntime`, and there doesn't seem to be a decaying function of any sort: I *suspect* that over time, `vruntime` just gets so big that any other process on the machine will prempt merging.
What is confusing to me is that it doesn't look like the machine has high CPU or anything... so there might be some other throttling at play here.

Here is a diff (before/after) restart taken from `/proc/pid/sched`

```
< se.exec_start                                :   24483426539.404075
< se.vruntime                                  :     135500227.539266
< se.sum_exec_runtime                          :       6469705.584427
---
> se.exec_start                                :   24481968085.667081
> se.vruntime                                  :        114133.444487
> se.sum_exec_runtime                          :            61.248399
7c7
< se.statistics.sleep_start                    :   24483426539.404075
---
> se.statistics.sleep_start                    :   24481968085.667081
9,18c9,18
< se.statistics.sleep_max                      :         48048.484286
< se.statistics.block_max                      :          3590.918983
< se.statistics.exec_max                       :             4.418723
< se.statistics.slice_max                      :           635.302620
< se.statistics.wait_max                       :            56.031742
< se.statistics.wait_sum                       :       2987576.124842
< se.statistics.wait_count                     :              1971004
< se.statistics.iowait_sum                     :         65030.711157
< se.statistics.iowait_count                   :                 3701
< se.nr_migrations                             :                17982
---
> se.statistics.sleep_max                      :         36793.094570
> se.statistics.block_max                      :             0.042922
> se.statistics.exec_max                       :             4.000239
> se.statistics.slice_max                      :             2.275626
> se.statistics.wait_max                       :             4.028972
> se.statistics.wait_sum                       :            15.890139
> se.statistics.wait_count                     :                   79
> se.statistics.iowait_sum                     :             0.000000
> se.statistics.iowait_count                   :                    0
> se.nr_migrations                             :                   11
21,30c21,30
< se.statistics.nr_failed_migrations_running   :                15896
< se.statistics.nr_failed_migrations_hot       :                18227
< se.statistics.nr_forced_migrations           :                 3617
< se.statistics.nr_wakeups                     :               196647
< se.statistics.nr_wakeups_sync                :               172692
< se.statistics.nr_wakeups_migrate             :                 7542
< se.statistics.nr_wakeups_local               :                20343
< se.statistics.nr_wakeups_remote              :               176304
< se.statistics.nr_wakeups_affine              :                 3146
< se.statistics.nr_wakeups_affine_attempts     :                14686
---
> se.statistics.nr_failed_migrations_running   :                    2
> se.statistics.nr_failed_migrations_hot       :                    1
> se.statistics.nr_forced_migrations           :                    0
> se.statistics.nr_wakeups                     :                   48
> se.statistics.nr_wakeups_sync                :                    0
> se.statistics.nr_wakeups_migrate             :                    9
> se.statistics.nr_wakeups_local               :                   15
> se.statistics.nr_wakeups_remote              :                   33
> se.statistics.nr_wakeups_affine              :                    2
> se.statistics.nr_wakeups_affine_attempts     :                   26
33,37c33,37
< avg_atom                                     :             3.300654
< avg_per_cpu                                  :           359.787875
< nr_switches                                  :              1960128
< nr_voluntary_switches                        :               196637
< nr_involuntary_switches                      :              1763491
---
> avg_atom                                     :             0.805899
> avg_per_cpu                                  :             5.568036
> nr_switches                                  :                   76
> nr_voluntary_switches                        :                   49
> nr_involuntary_switches                      :                   27
39,42c39,42
< se.avg.runnable_avg_sum                      :                 5352
< se.avg.runnable_avg_period                   :                47726
< se.avg.load_avg_contrib                      :                   37
< se.avg.decay_count                           :          23349215069
---
> se.avg.runnable_avg_sum                      :                 2652
> se.avg.runnable_avg_period                   :                47712
> se.avg.load_avg_contrib                      :                   15
> se.avg.decay_count                           :          23347824179
45c45
< clock-delta                                  :                  116
---
> clock-delta                                  :                  168
```

### PR DESCRIPTION
**Pull request by graydon**
# Description

Resolves #2128 -- there's a long story over there but the gist is we were queueing HASs that included a lot of `FutureBucket`s in `FB_LIVE_INPUTS` state that were actually done merging, and should be resolved to `FB_LIVE_OUTPUT` state before serializing and storing to the publish queue in the DB. This causes CPU spikes (and significantly delays publishing) by redoing merges in the dequeued-and-deserialized `FutureBucket`s before publishing.

The fix is to sink eager FutureBucket resolution into the BucketList itself -- in the `addBatch` routine -- so when anyone makes a HAS copy of it it's likely to have any finished merges (especially long-running ones) resolved.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
While this can help, it seems unlikely to make a big difference:
`maybeQueueHistoryCheckpoint` (step 1) is called before even calling `ltx.commit()` (step 2) in `LedgerManagerImpl::closeLedger`, so right after starting merges.

It seems to me that, in this particular situation, the problem is that `startMerge` (called from `hm.publishQueuedHistory` - step 3 in closeLedger) doesn't know that it's starting a merge already in progress.

**Comment by graydon** [comment]
@MonsieurNicolas it's not the merges in the current close (the one that get snapshotted into the publish queue) that are the problem. it's merges from _many_ ledger-closes ago. minutes, hours, days. _none_ of them get resolved anywhere on their own.

**Comment by MonsieurNicolas** [comment]
Ah yes this is indeed a pretty bad bug. So it looks like we also have the bug that I described (that I thought you were trying to fix): basically any *new* and expensive merges are done twice. A lot better than what you’re fixing here but still pretty bad.

**Comment by graydon** [comment]
@MonsieurNicolas updated with a test that fails with the old code and passes with the new.

File: src/history/HistoryManagerImpl.cpp [hunk 1]
```diff
@@ -251,7 +251,7 @@ void
 HistoryManagerImpl::queueCurrentHistory()
 {
     auto has = getLastClosedHistoryArchiveState();
-
+    has.resolveAnyReadyFutures();
```
Comment (marta-lokhova) [inline src/history/HistoryManagerImpl.cpp]: Should this be a bit tighter, i.e, in `getLastClosedHistoryArchiveState `?  (generally, I'm wondering what's the best place to do resolution to avoid having this issue elsewhere, e.g. by guaranteeing that latest HAS's state is up-to-date)

Comment (graydon) [reply src/history/HistoryManagerImpl.cpp]: @marta-lokhova it could definitely be moved inwards a bit in the logic; I avoided doing so out of expedience as many other code paths and tests are coupled to the choice of when to resolve and I was trying to get this done by the 11.2 release. As it happens we didn't take this for 11.2 so there's probably time to go back and fix all the things that are sensitive to the matter.

Comment (graydon) [reply src/history/HistoryManagerImpl.cpp]: @marta-lokhova ok, fixed! See if you like this variant better :)

**Comment by MonsieurNicolas** [comment]
r+ 6fade93bdba6960c99f9124bba6c760e28c8cc0d

**Comment by MonsieurNicolas** [comment]
needs clang-format

**Comment by MonsieurNicolas** [comment]
r+ f66d2dde4947361c080c84f66d466e488a4a8a24

**Comment by MonsieurNicolas** [comment]
@latobarita: retry
