### PR TITLE
Catch contract host panics, fix #3535

### LINKED ISSUE #3535: rust bridge: properly translate rust panics into C++ exception
Right now in `InvokeHostFunctionOpFrame::doApply` we assume that `rust_bridge` throws a `std::exception` when rust panics... but this does not seem to be the case

### PR DESCRIPTION
**Pull request by graydon**
This just adds an additional wrapper function on each of the contract host functions in core that calls `panic::catch_unwind` to trap any panics that we might accidentally be generating inside the contract host.

### CODE REVIEW

File: src/rust/src/contract.rs [hunk 1]
```diff
@@ -286,6 +302,20 @@ pub(crate) fn preflight_host_function(
     hf_buf: &CxxVector<u8>,
     args_buf: &CxxVector<u8>,
     cb: UniquePtr<PreflightCallbacks>,
+) -> Result<(), Box<dyn Error>> {
+    let res = panic::catch_unwind(panic::AssertUnwindSafe(|| {
+        preflight_host_function_or_maybe_panic(hf_buf, args_buf, cb)
+    }));
+    match res {
+        Err(_) => Err(ContractError::General("contract host panicked").into()),
```
Comment (leighmcculloch) [inline src/rust/src/contract.rs:310]: It is somewhat confusing that we have `ContractError` in the host which is host errors, as well as `Status::ContractError` which is only contract generated errors. This is my fault, I didn't see that we had `ContractError` here when I added the new variant to `Status`.

If we are to change either, it might be preferable if we can change the `ContractError` though, but maybe we can live with name clash.

**Review by leighmcculloch — APPROVED** [review]

File: src/rust/src/contract.rs (hunk 1 above)
Comment (graydon) [reply src/rust/src/contract.rs:310]: Oh, I can change this, not a big deal.

**Comment by sisuresh** [comment]
@graydon Were you able to test this against the host by inserting a panic? This LGTM btw.

**Comment by sisuresh** [comment]
r+ d421e1f4653ef45930e5ff5cabbadf9d77eb8adc
