### PR TITLE
Fixed assert failure when banning txs

### LINKED ISSUE #4421: Fix TxQueue bugs post TxFrame refactor
There are currently some asserts failing in TxQueue code following the transaction frame refactor. These should be addressed.

### PR DESCRIPTION
**Pull request by SirTyson**
# Description

Resolves #4421

Fixes an assert failure that occurred when a TX that exceeds ledger limits is banned.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/herder/test/TransactionQueueTests.cpp [hunk 1]
```diff
@@ -798,10 +798,17 @@ TEST_CASE("TransactionQueue hitting the rate limit",
...
+        REQUIRE(addResult.txResult->getResultCode() == txINSUFFICIENT_FEE);
+        REQUIRE(addResult.txResult->getResult().feeCharged == 300 * 3 + 1);
+    }
+    SECTION("cannot add - tx outside of limits")
+    {
+        auto tx = transaction(*app, account5, 1, 1, 100 * 1'000, 100);
+        auto addResult = testQueue.add(
+            tx, TransactionQueue::AddResultCode::ADD_STATUS_TRY_AGAIN_LATER);
+        REQUIRE(!addResult.txResult);
+        // REQUIRE(addResult.txResult->getResultCode() ==
```
Comment (SirTyson) [inline src/herder/test/TransactionQueueTests.cpp:810]: Remove comment?

**Review by SirTyson — COMMENTED** [review]
LGTM (but I can't approve because it's technically my PR lol)

File: src/herder/test/TransactionQueueTests.cpp (hunk 1 above)
Comment (marta-lokhova) [reply src/herder/test/TransactionQueueTests.cpp]: Done.

**Review by marta-lokhova — APPROVED** [review]
