### PR TITLE
Fix end-transaction iterator computation in fuzzer

### LINKED ISSUE #2928: Fuzzer bug when attemptToApplyOps is called with more than 100 operations.
https://github.com/stellar/stellar-core/blob/6b99ef893c7f13f22c7c72a7f66ea912aeb4ad73/src/test/FuzzerImpl.cpp#L532

`begin` should be `beginOpsInThisTx` on that line. This bug currently isn't being hit because `attemptToApplyOps` is never called with more than 100 operations. If it were hit, it would cause on infinite loop.

### PR DESCRIPTION
**Pull request by rokopt**
# Fix end-transaction iterator computation in fuzzer

Resolves #2928 

Had `attemptToApplyOps()` been called with more operations than would fit in a transaction, the second transaction would have computed the wrong `endOpsInThisTx`.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/test/FuzzerImpl.cpp [hunk 1]
```diff
@@ -529,7 +529,7 @@ attemptToApplyOps(LedgerTxn& ltx, PublicKey const& sourceAccount,
         auto endOpsInThisTx =
             std::distance(beginOpsInThisTx, end) <= MAX_OPS_PER_TX
                 ? end
-                : begin + MAX_OPS_PER_TX;
+                : beginOpsInThisTx + MAX_OPS_PER_TX;
```
Comment (jonjove) [inline src/test/FuzzerImpl.cpp:532]: While this fixes the problem, I don't think it's the best approach. Why did this bug happen? It happened because both `begin` and `beginOpsInThisTx` exist. As long as they both exist, this bug can happen again.

Perhaps having both exist was an unavoidable detail because you needed `begin` later. But you don't, so you might as well just remove `beginOpsInThisTx` entirely and use `begin`.

Comment (rokopt) [reply src/test/FuzzerImpl.cpp]: Agreed, that's significantly more elegant.  Done.

**Comment by jonjove** [comment]
r+ c13a39a
