### PR TITLE
Fix delete non existing offer

### LINKED ISSUE #1053: deleting an offer that doesn't exist should fail
```
{
  "_links": {
    "transaction": {
      "href": "https://horizon-testnet.stellar.org/transactions/0350a5ffc6ff006f45e49ec9a85626a6270a941136d4ac9f04f4e3691d75a6e2"
    }
  },
  "hash": "0350a5ffc6ff006f45e49ec9a85626a6270a941136d4ac9f04f4e3691d75a6e2",
  "ledger": 2797109,
  "envelope_xdr": "AAAAAPHu10nOw8i4f/7QRlBx02EWMhocMFLddz8Ly8G1297oAAAAZAAl7poAAAAEAAAAAAAAAAAAAAABAAAAAAAAAAMAAAABSlBZAAAAAADUiLVBMU000wcktFuXGojOuPkjSbzmm9wIUgtIOg5hkAAAAAFVU0QAAAAAANSItUExTTTTByS0W5caiM64+SNJvOab3AhSC0g6DmGQAAAAAAAAAAAAAABkAAAAAQAAAAAAAAAAAAAAAAAAAAG1297oAAAAQAR2ncOjZUfuGZklrA6sVNWu3EWiYOD2CV0qNzq3754bESOPn7aSNptTRRJ0ywYdX+C77vZU5lTOPn5/yMm2LgU=",
  "result_xdr": "AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAADAAAAAAAAAAAAAAACAAAAAA==",
  "result_meta_xdr": "AAAAAAAAAAEAAAAA"
}
```

If this has happened on the live network then it will require a feature flag

### PR DESCRIPTION
**Pull request by vogel**
Fixes #1053 

Some commits common with #1067

### CODE REVIEW

File: src/transactions/ManageOfferOpFrame.cpp [hunk 1]
```diff
@@ -156,6 +156,14 @@ ManageOfferOpFrame::doApply(Application& app,
     }
     else
     { // creating a new Offer
+        if (app.getLedgerManager().getCurrentLedgerVersion() > 2 && mManageOffer.amount == 0)
+        {
+            app.getMetrics().NewMeter({"op-manage-offer", "invalid", "create-with-zero"},
+                             "operation").Mark();
+            innerResult().code(MANAGE_OFFER_MALFORMED);
```
Comment (jedmccaleb) [inline src/transactions/ManageOfferOpFrame.cpp]: use MANAGE_OFFER_NOT_FOUND

Comment (vogel) [inline src/transactions/ManageOfferOpFrame.cpp]: updated, also changed place for this check to more appropiate

**Comment by vogel** [comment]
Chagned target branch
