### PR TITLE
Reduce noise in CI output

### LINKED ISSUE #4959: CI output is unnecessarily verbose
There are a lot of effectively empty lines in CI that make it harder to find a failing test case when one occurs.

### PR DESCRIPTION
**Pull request by drebelsky**
Resolves #4959. Removes in CI output, replace parallel `--line-buffer` with `--group` arg and remove `--progress`. Also, remove dot lines from `SimpleReporter` (in CI output).

### CODE REVIEW

File: src/test/selftest-parallel [hunk 1]
```diff
@@ -89,5 +92,8 @@ for i in $RUN_PARTITIONS; do
   cat $TEST_PARTITIONS_DIR/test-partition-$i.txt >> $TESTS
 done
 
-cat $TESTS | parallel -j $nparts -n $BATCHSIZE --line-buffer --tag-string '{%}' --progress --halt-on-error 2 runpart '{%}' "{}"
-
+PROGRESS=
+if [[ $PARALLEL_PROGRESS -ne 0 ]]; then
+    PROGRESS="--progress"
+fi
+cat $TESTS | parallel -j $nparts -n $BATCHSIZE --line-buffer --tag-string '{%}' $PROGRESS --halt-on-error 2 runpart '{%}' "{}"
```
Comment (graydon) [inline src/test/selftest-parallel]: I think it might be worth switching to --group from --line-buffer. on the one hand it doesn't output anything until the end, but on the other hand we typically only look once the thing has finished running, and having lines interleaved is often very confusing.

File: src/test/SimpleTestReporter.h [hunk 2]
```diff
@@ -11,6 +11,8 @@ namespace Catch
 
 struct SimpleTestReporter : public ConsoleReporter
 {
+    static bool disableDots;
```
Comment (bboston7) [inline src/test/SimpleTestReporter.h]: Nit: Following the convention of the codebase, this variable should be named `gDisableDots` to indicate it's a global variable.

**Review by bboston7 — DISMISSED** [review]
