### PR TITLE
Continue to capture SCP messages for previous ledger in database

### LINKED ISSUE #3769: Make it easier to capture SCP messages
Right now SCP messages go to 2 places:
* meta, as soon as we close a ledger
* history archives (via SCPHistory, as soon as we close a ledger)

This issue tracks improving the quality of the SCP messages uploaded to archives as it's the easiest of the two (we could emit SCP updates from older ledgers in the meta, but it seems a bit more involved).

The issue can be summarized as:
SCP messages that are emitted are the ones used by that node to externalize.
To externalize, the node needs to receive either `CONFIRM` or `EXTERNALIZE` messages from nodes in its quorum set.

Some systems (like bridges) rely on SCP messages, so the more `EXTERNALIZE` messages we can gather, the better it is (they're smaller and easier to process from contracts).

The proposal tracked here is to add a mechanism to core to improve the chances that we have `EXTERNALIZE` messages from as many validators in the transitive quorum as possible published to archive.

Given how the system works right now the following may work:
- [x] audit herder/SCP filtering logic to ensure that we continue to store `EXTERNALIZE` messages in memory after a ledger is closed. I think this is already the case (right now we accumulate those so that we can serve them to other peers).
- [x] add a new setting that controls a delay to publish to archive.
   * the delay could be expressed in terms of number of ledgers (anything less than `MAX_SLOTS_TO_REMEMBER`) or in time (maybe harder to configure/implement?) - in practice we probably need only a few more seconds to receive all messages (validators tend to track the same ledger)
- [ ] continue to save SCP messages in the database for older slots. Right now this only occurs [right when we externalize](https://github.com/stellar/stellar-core/blob/287fe4c5d7f7ebce1a327cd26f25dd5858cd37a0/src/herder/HerderImpl.cpp#L280)
       * after the delay, update the `scphistory` table to reflect the internal SCP state. we could compute the differences in terms of SCP messages (or just rewrite the whole thing? -- I don't know how much data we're really talking about here) for the effected slot
           *  note that we must write both when we externalize and later as we want to have in the database at least the messages that were used when externalizing in case of a crash.
       * the delay is also used to delay the actual snapshot (that produces files from database state) & publish step
   * this setting should probably not be set on validators, and only for watchers (we may fail to start on validators) as the delay can potentially put the network at risk of an outage

### PR DESCRIPTION
**Pull request by bboston7**
# Description

Resolves #3769

Upon closing a ledger, nodes record SCP messages received during the ledger period in the `scphistory` database table. However, any messages about that ledger heard *after* close were ignored. This change captures more of those messages by modifying the `processExternalized` function (which is responsible for recording SCP messages on ledger close) to also record any new messages heard about the previous ledger.

## Performance impact

As this change adds additional database interactions to the main thread, it does have a performance impact. I've mitigated this by [wrapping the new and old `saveSCPHistory` calls in a single transaction](https://github.com/stellar/stellar-core/blob/23aa763b643375322271496dea7f5be633b7a67f/src/herder/HerderImpl.cpp#L316). I measured the performance impacts using Tracy and have summarized the results for SQLite and Postgres below.

On SQLite, the use of a single transaction for both `saveSCPHistory` calls effectively negates the performance impact of the additional call. I suspect this is because it saves an expensive write to disk, which dominates the call.

On Postgres the performance improvement from using a single transaction is minimal, and does not entirely make up for the additional saveSCPHistory call. On average, saving the SCP history now takes 10% longer than before (averaging 0.82 miliseconds more on my machine). For reference, 0.82 milliseconds makes up 0.5% of the average `processExternalized` call when using the Postgres backend.

A 0.5% impact on one of two backends seemed like a good place to stop tweaking and measuring performance impacts, but if that's too large an impact I have a couple more ideas I can try:
1. Using a single multi-row insert into `scphistory` may be faster than the multiple single row inserts `saveSCPHistory` currently performs.
2. At first glance, it seems like saving SCP history could be moved off the main thread and onto a worker thread.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/herder/HerderImpl.h [hunk 1]
```diff
@@ -288,6 +289,10 @@ class HerderImpl : public Herder
     Application& mApp;
     LedgerManager& mLedgerManager;
 
+    // Set of nodes whose SCP messages from the previous ledger have already
+    // been stored in the scphistory database table.
+    UnorderedSet<NodeID> mPrevExternalizedEnvs;
```
Comment (marta-lokhova) [inline src/herder/HerderImpl.h:294]: This isn't _quite_ right: current implementation only records new statements from nodes we haven't heard from at all in the last consensus round. The scenario we also want to handle is when we receive _newer_ SCP messages from nodes in our quorum set. This can occur if, for example, we have CONFIRM messages from our quorum slice (which is enough to externalize that ledger), but then receive EXTERNALIZE messages from the same nodes after some time. We'd like to store those newer EXTERNALIZE messages as well, to make things easier for downstream systems (e.g. bridges). So I think we'd either want to store the diff in SCP messages, or rewrite the whole externalizing state, depending on the performance impact.

**Review by marta-lokhova — CHANGES_REQUESTED** [review]
Thanks for putting this together! I had a question regarding another scenario we'd want to handle

File: src/herder/HerderImpl.h (hunk 1 above)
Comment (bboston7) [reply src/herder/HerderImpl.h:294]: Ah, this was an oversight on my part, I forgot about that scenario. I'll fix this and do another round of performance testing.

Comment (bboston7) [reply src/herder/HerderImpl.h]: I pushed up a fix for this in 07defe8ceb992f810e47f5047ae60fd7dfb58dfe.  Weirdly enough the performance of rewriting the entire externalizing state is faster than tracking diffs. I think this is because rewriting can be done with a single `DELETE` followed by a single bulk `INSERT` (I changed `saveSCPHistory` to perform a single multi-row `INSERT` into `scphistory`, which provided a small performance improvement), while tracking diffs requires multiple `MODIFY`s and `INSERT`s.

Regardless, the performance impact of all of this isn't too bad. Compared to `master` on pubnet, the new process of saving SCP messages (doing two `saveSCPHistory` calls) takes ~3.7ms longer on Postgres and ~0.9ms longer on SQLite on my machine. In relative terms, that's 31% longer for Postgres and 50% longer for SQLite.

**Comment by MonsieurNicolas** [comment]
just a drive-by message wrt diff vs rewrite all of SCP state:
* right now tier1 contains I think 23 validators but we expect this to grow by 2-3x. That being said: if this becomes a problem, we could track (as a different issue) to change how/where we record SCP messages.
* on the txset front (not sure if it matters here)
   * with more validators we're more likely to encounter more (competing) TxSets
   * with TPS increase, txsets themselves are going to be bigger

**Comment by bboston7** [comment]
> * right now tier1 contains I think 23 validators but we expect this to grow by 2-3x. That being said: if this becomes a problem, we could track (as a different issue) to change how/where we record SCP messages.

Good point. I opened #4139 so we don't forget about this.

> * on the txset front (not sure if it matters here)
>   * with more validators we're more likely to encounter more (competing) TxSets
>   * with TPS increase, txsets themselves are going to be bigger

I don't think the number of competing TxSets will have much of an impact, as this only records the last externalizing message from any given validator. The only impact I could see is if we switched to the diff based approach and competing TxSets resulted in more frequent diffs. 

However, larger txsets might have an impact. I assume these txsets end up in the ballots in the `Value` field, thus making the ballots themselves larger. Is that right?

**Comment by bboston7** [comment]
> However, larger txsets might have an impact. I assume these txsets end up in the ballots in the `Value` field, thus making the ballots themselves larger. Is that right?

Actually, it looks like the SCP envelopes contain only the [hash of the txset](https://github.com/stellar/stellar-xdr/blob/bb54e505f814386a3f45172e0b7e95b7badbe969/Stellar-ledger.x#L29). In that case, I don't think txset size has any impact on saving envelopes to the database.

File: src/herder/test/HerderTests.cpp [hunk 2]
```diff
@@ -5803,3 +5803,117 @@ TEST_CASE("exclude transactions by operation type", "[herder]")
...
+    simulation->crankUntil(
+        [&]() {
+            return A->getLedgerManager().getLastClosedLedgerNum() == 3 &&
+                   B->getLedgerManager().getLastClosedLedgerNum() == 3;
+        },
+        2 * Herder::EXP_LEDGER_TIMESPAN_SECONDS, false);
+
+    // A and B should now have 3 entries in their scphistory table for ledger 2.
+    REQUIRE(getNumSCPHistoryEntries(A, 2) == 3);
+    REQUIRE(getNumSCPHistoryEntries(B, 2) == 3);
```
Comment (SirTyson) [inline src/herder/test/HerderTests.cpp:5918]: Should we check that C does not have extra copies of messages? I might have missed something but I think this may be possible.

**Review by SirTyson — COMMENTED** [review]
Looks good! Just a few nit pics and questions.

File: src/herder/HerderPersistenceImpl.cpp [hunk 3]
```diff
@@ -76,21 +81,28 @@ HerderPersistenceImpl::saveSCPHistory(uint32_t seq,
...
 
+        nodeIDs.push_back(nodeIDStrKey);
+        seqs.push_back(seq);
+        envelopes.push_back(envelopeEncoded);
+    }
+
+    if (!envs.empty())
+    {
+        // Perform multi-row insert into scphistory
         auto prepEnv =
```
[the remark this answers is not in the document]
Comment (bboston7) [reply src/herder/HerderPersistenceImpl.cpp:92]: This handles the collision case by [deleting all entries from `currentLedger` before performing the `INSERT`](https://github.com/bboston7/stellar-core/blob/07defe8ceb992f810e47f5047ae60fd7dfb58dfe/src/herder/HerderPersistenceImpl.cpp#L54). This also resolves the `CONFIRM` vs `EXTERNALIZE` issue.

File: src/herder/test/HerderTests.cpp (hunk 2 above)
Comment (bboston7) [reply src/herder/test/HerderTests.cpp:5918]: Good idea to explicitly check this case. I added a test for this in d39400b30d1c195b1968a090fe6fb033a8752b08.

File: src/herder/HerderImpl.cpp [hunk 4]
```diff
@@ -307,10 +307,28 @@ HerderImpl::processExternalized(uint64 slotIndex, StellarValue const& value,
     // save the SCP messages in the database
     if (mApp.getConfig().MODE_STORES_HISTORY_MISC)
     {
+        ZoneNamedN(updateSCPHistoryZone, "update SCP history", true);
+
+        // NOTE: Consolidating the two saveSCPHistory calls into one transaction
+        // provides modest performance increases for sqlite and insignificant
+        // performance increases for postgres.
+        soci::transaction txscope(mApp.getDatabase().getSession());
```
[the remark this answers is not in the document]
Comment (bboston7) [reply src/herder/HerderImpl.cpp]: Done in c950e1c06e44f7234e7cc1bc7e1ab7c5f98b08ea

File: src/herder/test/HerderTests.cpp [hunk 5]
```diff
@@ -5803,3 +5803,117 @@ TEST_CASE("exclude transactions by operation type", "[herder]")
...
+    };
+
+    // A and B should have 2 entries in their scphistory table for ledger 2. C
+    // should have 0.
+    REQUIRE(getNumSCPHistoryEntries(A, 2) == 2);
+    REQUIRE(getNumSCPHistoryEntries(B, 2) == 2);
+    REQUIRE(getNumSCPHistoryEntries(C, 2) == 0);
+
+    // Get messages from A and B
+    HerderImpl* herderA = dynamic_cast<HerderImpl*>(&A->getHerder());
```
[the remark this answers is not in the document]
Comment (bboston7) [reply src/herder/test/HerderTests.cpp]: Done in c950e1c06e44f7234e7cc1bc7e1ab7c5f98b08ea

File: src/herder/test/HerderTests.cpp [hunk 6]
```diff
@@ -5803,3 +5803,126 @@ TEST_CASE("exclude transactions by operation type", "[herder]")
...
+
+    // Crank A and B until they're on ledger 2
+    simulation->crankUntil(
+        [&]() {
+            return A->getLedgerManager().getLastClosedLedgerNum() == 2 &&
+                   B->getLedgerManager().getLastClosedLedgerNum() == 2;
+        },
+        2 * Herder::EXP_LEDGER_TIMESPAN_SECONDS, false);
+
+    // Return the number of entires in a node's scphistory table for the given
```
Comment (SirTyson) [inline src/herder/test/HerderTests.cpp:5851]: Nit: "entires"

**Review by SirTyson — APPROVED** [review]
Minor typo, but LGTM, thanks!

File: src/herder/test/HerderTests.cpp (hunk 6 above)
Comment (bboston7) [reply src/herder/test/HerderTests.cpp]: Fixed in 72b875763825ddd0d230e819847c625f8c04999b

**Comment by bboston7** [comment]
I just rebased this on top of `master` and squashed down to a single commit

**Review by marta-lokhova — CHANGES_REQUESTED** [review]
Thanks for the change! Left a few suggestions. Let's plan to ship this change in 20.2.0

File: src/herder/HerderImpl.cpp [hunk 7]
```diff
@@ -307,10 +307,28 @@ HerderImpl::processExternalized(uint64 slotIndex, StellarValue const& value,
     // save the SCP messages in the database
     if (mApp.getConfig().MODE_STORES_HISTORY_MISC)
     {
+        ZoneNamedN(updateSCPHistoryZone, "update SCP history", true);
+
+        // NOTE: Consolidating the two saveSCPHistory calls into one transaction
+        // provides modest performance increases for sqlite and insignificant
+        // performance increases for postgres.
+        soci::transaction txScope(mApp.getDatabase().getSession());
```
[the remark this answers is not in the document]
Comment (bboston7) [reply src/herder/HerderImpl.cpp]: Done in a8139eda1f54ce59df7f1bf04b89c71d862e72fa

File: src/herder/test/HerderTests.cpp [hunk 8]
```diff
@@ -5803,3 +5803,126 @@ TEST_CASE("exclude transactions by operation type", "[herder]")
...
+
+    // Crank A and B until they're on ledger 3
+    simulation->crankUntil(
+        [&]() {
+            return A->getLedgerManager().getLastClosedLedgerNum() == 3 &&
+                   B->getLedgerManager().getLastClosedLedgerNum() == 3;
+        },
+        2 * Herder::EXP_LEDGER_TIMESPAN_SECONDS, false);
+
+    // A and B should now have 3 entries in their scphistory table for ledger 2.
```
[the remark this answers is not in the document]
Comment (bboston7) [reply src/herder/test/HerderTests.cpp]: Done in a8139eda1f54ce59df7f1bf04b89c71d862e72fa

**Review by marta-lokhova — APPROVED** [review]

**Comment by marta-lokhova** [comment]
r+ a8139eda1f54ce59df7f1bf04b89c71d862e72fa

**Comment by bboston7** [comment]
The test failed because it was overly sensitive to the rng seed. I fixed it by increasing some timeouts in the test and also better specifying the state of `A` and `B` to be insensitive to leader election.

**Comment by marta-lokhova** [comment]
r+ 26bba350feed57eb19241f22d932eacf266a41a3

**Comment by marta-lokhova** [comment]
r+ 26bba350feed57eb19241f22d932eacf266a41a3
