### PR TITLE
Account for background work when in virtual time

### LINKED ISSUE #4755: tests: add support for parallel ledger close when in virtual time
Currently, when advancing the clock in virtual time, we ignore the work done by the ledger close thread. This should be addressed so that tests can run in loopback mode—which is significantly faster than TCP mode.

### LINKED ISSUE #4943: Intermittent CI failure for "trigger next ledger side effects"
In two CI runs([run 1](https://github.com/stellar/stellar-core/actions/runs/17984168583/job/51157951268), [run 2](https://github.com/stellar/stellar-core/actions/runs/17959232680/attempts/1)), the test "trigger next ledger side effects" failed, but the subsequent runs for both jobs passed.

```
-------------------------------------------------------------------------------
trigger next ledger side effects
-------------------------------------------------------------------------------
herder/test/HerderTests.cpp:6598
...............................................................................

herder/test/HerderTests.cpp:6603: FAILED:
due to unexpected exception with message:
  Simulation timed out

<done>
===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed
```

I was, however, unable to reproduce either failure locally,.

### PR DESCRIPTION
**Pull request by marta-lokhova**
Resolves #4755 
Resolves #4943

### CODE REVIEW

File: src/util/test/TimerTests.cpp [hunk 1]
```diff
@@ -97,6 +97,44 @@ TEST_CASE("VirtualClock from_time_t", "[timer]")
...
+    std::atomic<int> backgroundTasks{0};
+
+    VirtualTimer timer1(app);
+    timer1.expires_from_now(std::chrono::milliseconds(100));
+    timer1.async_wait([&](asio::error_code const& e) {
+        REQUIRE(backgroundTasks == 1);
+        timerFired = true;
+    });
+
+    app.postOnLedgerCloseThread(
```
Comment (SirTyson) [inline src/util/test/TimerTests.cpp]: Nit: just use app->

File: src/util/test/TimerTests.cpp [hunk 2]
```diff
@@ -97,6 +97,44 @@ TEST_CASE("VirtualClock from_time_t", "[timer]")
...
+
+    VirtualClock clock;
+    Application::pointer appPtr = createTestApplication(clock, cfg);
+    // cancel the timer
+    appPtr->getHerder().shutdown();
+    // cancel the demand timer for tx pull-mode flooding
+    appPtr->getOverlayManager().shutdown();
+    Application& app = *appPtr;
+
+    bool timerFired = false;
```
Comment (SirTyson) [inline src/util/test/TimerTests.cpp]: This should be atomic

File: src/util/test/TimerTests.cpp [hunk 3]
```diff
@@ -97,6 +97,44 @@ TEST_CASE("VirtualClock from_time_t", "[timer]")
     CHECK(now == VirtualClock::from_time_t(133818));
 }
 
+#ifdef USE_POSTGRES
+TEST_CASE("virtual time with background work", "[timer]")
```
Comment (SirTyson) [inline src/util/test/TimerTests.cpp:101]: I think a block comment describing what this is testing would be helpful

File: src/util/Timer.cpp [hunk 4]
```diff
@@ -417,7 +418,7 @@ VirtualClock::crank(bool block)
         // If we didn't make progress and caller wants blocking, block now.
         progressCount += mIOContext.run_one();
     }
-    return progressCount;
+    return progressCount + mBackgroundWorkCount.load();
```
Comment (SirTyson) [inline src/util/Timer.cpp]: Can we hide the load behind `mMode == VIRTUAL_TIME`? Given that it's an atomic, I'd rather not have a synchronized access for a testing only value be in every call to `crank`.

File: src/main/ApplicationImpl.cpp [hunk 5]
```diff
@@ -1496,11 +1496,13 @@ ApplicationImpl::postOnLedgerCloseThread(std::function<void()>&& f,
                                          std::string jobName)
 {
     releaseAssert(mLedgerCloseIOContext);
+    getClock().newBackgroundWork();
```
Comment (SirTyson) [inline src/main/ApplicationImpl.cpp:1499]: Should these also be added to all the other thread post functions?

**Review by SirTyson — CHANGES_REQUESTED** [review]
Looks good to me, thanks for fixing the tests! Just a couple small things and a question or two.

File: src/main/ApplicationImpl.cpp (hunk 5 above)
Comment (marta-lokhova) [reply src/main/ApplicationImpl.cpp:1499]: I don't think so - for other types of background work, main thread controls completion of tasks, which means the existing cranking mechanism should work as expected even if there's unfinished background work.

**Comment by marta-lokhova** [comment]
@SirTyson all your feedback should be addressed now.

File: src/main/ApplicationImpl.cpp (hunk 5 above)
Comment (SirTyson) [reply src/main/ApplicationImpl.cpp:1499]: I don't think this applies to FutureBucket work. In any case, I think a comment describing why `newBackgroundWork()` and `finishedBackgroundWork()` are required here but not elsewhere would be nice. Currently there's not a lot of context as to what this function does and it would look like a bug that some background works call it while others do not.

Comment (marta-lokhova) [reply src/main/ApplicationImpl.cpp:1499]: I don't think FutureBucket work needs this new functionality. The result of bucket merges is controlled by the main thread (via futures), so this should ensure event loop is executed in the right order. I mean, there shouldn't be any harm in counting background work for all threads just for code consistency, but it's not strictly needed.
