### PR TITLE
bug 1099 - consolidate PRNG use in tests and make seedable.

### LINKED ISSUE #1099: Make tests use randomized NodeIDs and AccountIDs
As shown in Force SCP, the result of tests sometimes depends on generated NodeID (for some values of NodeIDs in Force SCP a third node is chosen as round leader over and over again which timeouts the tests).

It is possible that similar issues would be found in other tests if ID for nodes (and possibly accounts) were not hardcoded but chosen at random.

### PR DESCRIPTION
**Pull request by graydon**
# Description

This switches all uses of PRNGs in testing to the single global PRNG and adds support for manual seeding on the command-line. Additionally it reports the seed at the end of a run that ends in failure, so that you can run tests in a shell while-loop passing random seeds and it will conveniently break on the first nondeterministic failure. Should help shake out tests that are only passing due to lucky configuration of the (currently default-seeded) PRNGs.

Resolves #1099 

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] N/A If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

File: src/invariant/test/ConservationOfLumensTests.cpp [hunk 1]
```diff
@@ -161,13 +159,13 @@ TEST_CASE("Account balances changed without inflation",
         std::vector<LedgerEntry> entries1;
         std::generate_n(std::back_inserter(entries1), N,
                         std::bind(generateRandomAccount, 2));
-        entries1 = updateBalances(entries1, *app, gen);
+        entries1 = updateBalances(entries1, *app, gRandomEngine);
```
Comment (vogel) [inline src/invariant/test/ConservationOfLumensTests.cpp]: Is there a reason to pass gRandomEngine in here?
If we must always use the global one, let just use it inside updateBalances as well instead of parameter gen (applies also to other functions and methods).

**Comment by vogel** [comment]
There are also a few calls of plain std::rand() in the code - do these need to migrate to gRandomEngine as well?

File: src/invariant/test/ConservationOfLumensTests.cpp (hunk 1 above)
Comment (graydon) [reply src/invariant/test/ConservationOfLumensTests.cpp]: Fair, fixed.

**Comment by graydon** [comment]
Concerning the use of the global system PRNG via `std::rand()`, Catch already seeds it (via `std::srand()`) when given the `--rng-seed` option. This is just extending that seeding process to our own `gRandomEngine`.

**Comment by graydon** [comment]
(Pushed update with changes requested. Anything else or is this good to go?)

File: src/crypto/SecretKey.cpp [hunk 2]
```diff
@@ -149,6 +150,20 @@ SecretKey::random()
     return sk;
 }
 
+SecretKey
```
Comment (MonsieurNicolas) [inline src/crypto/SecretKey.cpp]: should we ifdef this stuff with `BUILD_TESTS` or move to a test only file?

File: src/test/test.cpp [hunk 3]
```diff
@@ -251,10 +261,18 @@ runTest(CommandLineArgs const& args)
     {
         gVersionsToTest.emplace_back(Config::CURRENT_LEDGER_PROTOCOL_VERSION);
     }
+    if (seed != 0)
```
Comment (MonsieurNicolas) [inline src/test/test.cpp]: I *think* a better way (or in addition to) is to use https://github.com/catchorg/Catch2/blob/master/docs/event-listeners.md#top
and set the seed every time we run a test or do something clever when sections start.

Without this, we still have non deterministic behavior of some tests (that depend on real clock) that bleed into other tests

Comment (MonsieurNicolas) [reply src/test/test.cpp]: IF it's not already the case, we can do the same thing to `std::rand()`

File: src/crypto/SecretKey.cpp (hunk 2 above)
Comment (graydon) [reply src/crypto/SecretKey.cpp]: Oh, perhaps. Will look at that.

File: src/test/test.cpp (hunk 3 above)
Comment (graydon) [reply src/test/test.cpp]: Oh, interesting! I will take a look, thanks!

**Comment by MonsieurNicolas** [comment]
We should probably revive and merge this as it helps with tests stability @graydon

File: src/test/test.cpp (hunk 3 above)
Comment (graydon) [reply src/test/test.cpp]: Fixed.

File: src/crypto/SecretKey.cpp (hunk 2 above)
Comment (graydon) [reply src/crypto/SecretKey.cpp]: Fixed.

**Comment by graydon** [comment]
@MonsieurNicolas Sorry this took so long, there were a lot of fussy details concerning the persistent test configs. Looks like it's all worked out now though.

**Comment by MonsieurNicolas** [comment]
r+ 7e8d137eacff9230fac38505096213692c6fac73
